# Reference appendices for the course.

from content_kanji import KANJI

APPENDICES = []

# ---------- Hiragana ----------
APPENDICES.append({
    'id': 'hiragana',
    'title': 'Hiragana Chart',
    'intro': 'The complete hiragana syllabary. Tap any character to hear it pronounced.',
    'sections': [
        {'type': 'h3', 'text': 'Base kana (46 characters)'},
        {'type': 'kana', 'rows': [
            [('あ','a'),('い','i'),('う','u'),('え','e'),('お','o')],
            [('か','ka'),('き','ki'),('く','ku'),('け','ke'),('こ','ko')],
            [('さ','sa'),('し','shi'),('す','su'),('せ','se'),('そ','so')],
            [('た','ta'),('ち','chi'),('つ','tsu'),('て','te'),('と','to')],
            [('な','na'),('に','ni'),('ぬ','nu'),('ね','ne'),('の','no')],
            [('は','ha'),('ひ','hi'),('ふ','fu'),('へ','he'),('ほ','ho')],
            [('ま','ma'),('み','mi'),('む','mu'),('め','me'),('も','mo')],
            [('や','ya'),None,('ゆ','yu'),None,('よ','yo')],
            [('ら','ra'),('り','ri'),('る','ru'),('れ','re'),('ろ','ro')],
            [('わ','wa'),None,None,None,('を','wo/o')],
            [('ん','n'),None,None,None,None],
        ]},
        {'type': 'h3', 'text': 'Voiced sounds — dakuten (゛) and handakuten (゜)'},
        {'type': 'kana', 'rows': [
            [('が','ga'),('ぎ','gi'),('ぐ','gu'),('げ','ge'),('ご','go')],
            [('ざ','za'),('じ','ji'),('ず','zu'),('ぜ','ze'),('ぞ','zo')],
            [('だ','da'),('ぢ','ji'),('づ','zu'),('で','de'),('ど','do')],
            [('ば','ba'),('び','bi'),('ぶ','bu'),('べ','be'),('ぼ','bo')],
            [('ぱ','pa'),('ぴ','pi'),('ぷ','pu'),('ぺ','pe'),('ぽ','po')],
        ]},
        {'type': 'p', 'text': 'Combo kana (yōon): small や, ゆ, よ follow an <i>i</i>-row kana (き, し, ち, に, ひ, み, り, ぎ, じ, び, ぴ) to form a single syllable. Examples: <span class="inline-jp">きゃ (kya), しゅ (shu), ちょ (cho), ぎょ (gyo), りゃ (rya), じゅ (ju)</span>.'},
    ],
})

# ---------- Katakana ----------
APPENDICES.append({
    'id': 'katakana',
    'title': 'Katakana Chart',
    'intro': 'The katakana syllabary — same sounds as hiragana, used for loan words, foreign names, scientific terms, and emphasis.',
    'sections': [
        {'type': 'h3', 'text': 'Base kana'},
        {'type': 'kana', 'rows': [
            [('ア','a'),('イ','i'),('ウ','u'),('エ','e'),('オ','o')],
            [('カ','ka'),('キ','ki'),('ク','ku'),('ケ','ke'),('コ','ko')],
            [('サ','sa'),('シ','shi'),('ス','su'),('セ','se'),('ソ','so')],
            [('タ','ta'),('チ','chi'),('ツ','tsu'),('テ','te'),('ト','to')],
            [('ナ','na'),('ニ','ni'),('ヌ','nu'),('ネ','ne'),('ノ','no')],
            [('ハ','ha'),('ヒ','hi'),('フ','fu'),('ヘ','he'),('ホ','ho')],
            [('マ','ma'),('ミ','mi'),('ム','mu'),('メ','me'),('モ','mo')],
            [('ヤ','ya'),None,('ユ','yu'),None,('ヨ','yo')],
            [('ラ','ra'),('リ','ri'),('ル','ru'),('レ','re'),('ロ','ro')],
            [('ワ','wa'),None,None,None,('ヲ','wo')],
            [('ン','n'),None,None,None,None],
        ]},
        {'type': 'h3', 'text': 'Voiced sounds'},
        {'type': 'kana', 'rows': [
            [('ガ','ga'),('ギ','gi'),('グ','gu'),('ゲ','ge'),('ゴ','go')],
            [('ザ','za'),('ジ','ji'),('ズ','zu'),('ゼ','ze'),('ゾ','zo')],
            [('ダ','da'),('ヂ','ji'),('ヅ','zu'),('デ','de'),('ド','do')],
            [('バ','ba'),('ビ','bi'),('ブ','bu'),('ベ','be'),('ボ','bo')],
            [('パ','pa'),('ピ','pi'),('プ','pu'),('ペ','pe'),('ポ','po')],
        ]},
        {'type': 'p', 'text': 'The long-vowel mark <b>ー</b> (never a repeated vowel) marks a long vowel in katakana. Example: <span class="inline-jp">コーヒー</span> (koohii, coffee), <span class="inline-jp">ビール</span> (biiru, beer).'},
    ],
})

# ---------- 100 Kanji ----------
APPENDICES.append({
    'id': 'kanji-100',
    'title': '100 N5 Kanji Reference',
    'intro': 'The 100 kanji taught in weeks 11 and 12, numbered in order of appearance. Tap any kanji to hear it spoken.',
    'sections': [
        {'type': 'kanji-grid', 'startAt': 1, 'items': KANJI},
    ],
})

# ---------- Grammar cheat sheet ----------
APPENDICES.append({
    'id': 'grammar',
    'title': 'Grammar Cheat Sheet',
    'intro': 'Every grammar point from the twelve-week course, on one page.',
    'sections': [
        {'type': 'h2', 'text': 'Particles'},
        {'type': 'table', 'headers': ['Particle', 'Marks', 'Example'], 'rows': [
            ['は (wa)', 'Topic', '<span class="inline-jp">わたしは がくせいです</span>'],
            ['が', 'Subject (new information, in focus)', '<span class="inline-jp">ねこが います</span>'],
            ['を (o)', 'Direct object', '<span class="inline-jp">パンを たべます</span>'],
            ['に', 'Destination / time / location of existence / indirect object', '<span class="inline-jp">7じに おきます</span>'],
            ['で', 'Location of action / means', '<span class="inline-jp">カフェで よみます</span>'],
            ['へ (e)', 'Direction toward', '<span class="inline-jp">とうきょうへ いきます</span>'],
            ['と', '&ldquo;And&rdquo; between nouns, &ldquo;with&rdquo; a person', '<span class="inline-jp">ともだちと いきます</span>'],
            ['も', '&ldquo;Also / too&rdquo;', '<span class="inline-jp">わたしも がくせいです</span>'],
            ['か', 'Yes/no question marker (sentence-final)', '<span class="inline-jp">げんきですか</span>'],
            ['の', 'Possession / modification', '<span class="inline-jp">わたしの ほん</span>'],
            ['から', 'From (place or time)', '<span class="inline-jp">アメリカから</span>'],
            ['まで', 'Until / up to', '<span class="inline-jp">5じまで</span>'],
        ]},
        {'type': 'h2', 'text': 'Verb conjugation — the polite forms'},
        {'type': 'table', 'headers': ['Form', 'Pattern', 'Example (たべる)'], 'rows': [
            ['Present / future (positive)', '~ます', '<span class="inline-jp">たべます</span> — eats, will eat'],
            ['Present / future (negative)', '~ません', '<span class="inline-jp">たべません</span>'],
            ['Past (positive)', '~ました', '<span class="inline-jp">たべました</span>'],
            ['Past (negative)', '~ませんでした', '<span class="inline-jp">たべませんでした</span>'],
            ['Te-form', 'See te-form rules', '<span class="inline-jp">たべて</span>'],
            ['Progressive / state', '~ています', '<span class="inline-jp">たべています</span> — am eating'],
            ['Request', '~てください', '<span class="inline-jp">たべてください</span> — please eat'],
        ]},
        {'type': 'h3', 'text': 'Te-form rules by verb group'},
        {'type': 'table', 'headers': ['Group', 'Rule', 'Examples'], 'rows': [
            ['Group 2 (ichidan)', 'drop る, add て', '<span class="inline-jp">たべる → たべて、みる → みて</span>'],
            ['Group 3 (irregular)', 'memorise', '<span class="inline-jp">する → して、くる → きて</span>'],
            ['Group 1: う / つ / る ending', '→ って', '<span class="inline-jp">あう → あって、まつ → まって</span>'],
            ['Group 1: ぶ / む / ぬ ending', '→ んで', '<span class="inline-jp">よむ → よんで、あそぶ → あそんで</span>'],
            ['Group 1: く ending', '→ いて (exception いく → いって)', '<span class="inline-jp">かく → かいて</span>'],
            ['Group 1: ぐ ending', '→ いで', '<span class="inline-jp">およぐ → およいで</span>'],
            ['Group 1: す ending', '→ して', '<span class="inline-jp">はなす → はなして</span>'],
        ]},
        {'type': 'h2', 'text': 'Adjective conjugation'},
        {'type': 'h3', 'text': 'い-adjectives'},
        {'type': 'table', 'headers': ['Form', 'Pattern', 'Example (おいしい)'], 'rows': [
            ['Present', '~い(です)', '<span class="inline-jp">おいしい(です)</span>'],
            ['Negative', '~くない(です)', '<span class="inline-jp">おいしくない(です)</span>'],
            ['Past', '~かった(です)', '<span class="inline-jp">おいしかった(です)</span>'],
            ['Past negative', '~くなかった(です)', '<span class="inline-jp">おいしくなかった(です)</span>'],
            ['Modifying a noun', 'attach directly', '<span class="inline-jp">おいしい りょうり</span>'],
        ]},
        {'type': 'p', 'text': '<b>Note:</b> いい (good) is irregular — the stem for conjugation is よ: よくない, よかった, よくなかった.'},
        {'type': 'h3', 'text': 'な-adjectives'},
        {'type': 'table', 'headers': ['Form', 'Pattern', 'Example (しずか)'], 'rows': [
            ['Present', '~です', '<span class="inline-jp">しずかです</span>'],
            ['Negative', '~じゃないです', '<span class="inline-jp">しずかじゃないです</span>'],
            ['Past', '~でした', '<span class="inline-jp">しずかでした</span>'],
            ['Past negative', '~じゃなかったです', '<span class="inline-jp">しずかじゃなかったです</span>'],
            ['Modifying a noun', 'add な before the noun', '<span class="inline-jp">しずかな へや</span>'],
        ]},
        {'type': 'h2', 'text': 'Common sentence patterns'},
        {'type': 'ul', 'items': [
            '<b>Statement:</b> [Topic] は [Comment] です。',
            '<b>Yes/no question:</b> [Statement] + か。',
            '<b>Where did you go?</b> どこへ いきましたか。',
            '<b>What did you do?</b> なにを しましたか。',
            '<b>Please do X:</b> [verb te-form] + ください。',
            '<b>I am doing / I do X regularly:</b> [verb te-form] + います。',
            '<b>Chaining actions:</b> [verb te-form], [verb te-form], [final verb in tense].',
        ]},
    ],
})

# ---------- Vocabulary index ----------
APPENDICES.append({
    'id': 'vocab-index',
    'title': 'Vocabulary Index',
    'intro': 'Thematic index of key vocabulary from the twelve-week course. Use the Hide English toggle to self-test.',
    'sections': [
        {'type': 'h3', 'text': 'Greetings & social'},
        {'type': 'vocab', 'rows': [
            ('おはよう / おはようございます','ohayou / ohayou gozaimasu','good morning (casual / polite)'),
            ('こんにちは','konnichiwa','hello / good afternoon'),
            ('こんばんは','konbanwa','good evening'),
            ('おやすみなさい','oyasumi nasai','good night'),
            ('さようなら','sayounara','goodbye'),
            ('ありがとう / ありがとうございます','arigatou / arigatou gozaimasu','thank you'),
            ('どういたしまして','dou itashimashite','you&rsquo;re welcome'),
            ('すみません','sumimasen','excuse me / sorry'),
            ('ごめんなさい','gomen nasai','I&rsquo;m sorry'),
            ('はい','hai','yes'),
            ('いいえ','iie','no'),
            ('はじめまして','hajimemashite','nice to meet you'),
            ('どうぞよろしくおねがいします','douzo yoroshiku onegaishimasu','please treat me well'),
            ('おげんきですか','ogenki desu ka','how are you?'),
            ('げんきです','genki desu','I&rsquo;m fine'),
            ('いただきます','itadakimasu','said before eating'),
            ('ごちそうさまでした','gochisousama deshita','said after eating'),
            ('いってきます','ittekimasu','said when leaving home'),
            ('いってらっしゃい','itterasshai','said to someone leaving'),
            ('ただいま','tadaima','I&rsquo;m home'),
            ('おかえりなさい','okaerinasai','welcome back'),
        ]},
        {'type': 'h3', 'text': 'People'},
        {'type': 'vocab', 'rows': [
            ('わたし','watashi','I / me'),
            ('あなた','anata','you (use sparingly)'),
            ('かれ','kare','he / boyfriend'),
            ('かのじょ','kanojo','she / girlfriend'),
            ('ひと','hito','person'),
            ('ともだち','tomodachi','friend'),
            ('かぞく','kazoku','family'),
            ('ちち / おとうさん','chichi / otousan','my father / someone&rsquo;s father'),
            ('はは / おかあさん','haha / okaasan','my mother / someone&rsquo;s mother'),
            ('あに / おにいさん','ani / oniisan','older brother'),
            ('あね / おねえさん','ane / oneesan','older sister'),
            ('おとうと','otouto','younger brother'),
            ('いもうと','imouto','younger sister'),
            ('こども','kodomo','child'),
            ('おとこの ひと','otoko no hito','man'),
            ('おんなの ひと','onna no hito','woman'),
            ('せんせい','sensei','teacher'),
            ('がくせい','gakusei','student'),
            ('かいしゃいん','kaishain','office worker'),
            ('いしゃ','isha','doctor'),
            ('エンジニア','enjinia','engineer'),
            ('コック / 料理人','kokku / ryourinin','cook'),
        ]},
        {'type': 'h3', 'text': 'Nationalities & countries'},
        {'type': 'vocab', 'rows': [
            ('日本 / にほん','nihon','Japan'),
            ('日本人 / にほんじん','nihon-jin','Japanese person'),
            ('アメリカ','amerika','America'),
            ('アメリカ人','amerika-jin','American'),
            ('イギリス','igirisu','UK / Britain'),
            ('イギリス人','igirisu-jin','British person'),
            ('フランス','furansu','France'),
            ('ちゅうごく','chuugoku','China'),
            ('かんこく','kankoku','Korea'),
            ('スペイン','supein','Spain'),
            ('イタリア','itaria','Italy'),
            ('ドイツ','doitsu','Germany'),
            ('カナダ','kanada','Canada'),
            ('メキシコ','mekishiko','Mexico'),
            ('ブラジル','burajiru','Brazil'),
            ('インド','indo','India'),
            ('タイ','tai','Thailand'),
            ('ベトナム','betonamu','Vietnam'),
        ]},
        {'type': 'h3', 'text': 'Everyday things'},
        {'type': 'vocab', 'rows': [
            ('ほん','hon','book'),
            ('ペン','pen','pen'),
            ('えんぴつ','enpitsu','pencil'),
            ('ノート','nooto','notebook'),
            ('かばん','kaban','bag'),
            ('くつ','kutsu','shoes'),
            ('ようふく','youfuku','clothes'),
            ('でんわ / けいたい','denwa / keitai','telephone / mobile phone'),
            ('コンピューター','konpyuutaa','computer'),
            ('カメラ','kamera','camera'),
            ('テレビ','terebi','TV'),
            ('くるま','kuruma','car'),
            ('じてんしゃ','jitensha','bicycle'),
            ('いえ / うち','ie / uchi','house / home'),
            ('かいしゃ','kaisha','company'),
            ('がっこう','gakkou','school'),
            ('えき','eki','train station'),
            ('みせ','mise','shop'),
            ('カフェ','kafe','café'),
            ('レストラン','resutoran','restaurant'),
            ('こうえん','kouen','park'),
            ('スーパー','suupaa','supermarket'),
            ('ぎんこう','ginkou','bank'),
            ('びょういん','byouin','hospital'),
            ('ゆうびんきょく','yuubinkyoku','post office'),
            ('ホテル','hoteru','hotel'),
            ('トイレ','toire','toilet'),
        ]},
        {'type': 'h3', 'text': 'Food & drink'},
        {'type': 'vocab', 'rows': [
            ('ごはん','gohan','rice / meal'),
            ('あさごはん','asagohan','breakfast'),
            ('ひるごはん','hirugohan','lunch'),
            ('ばんごはん','bangohan','dinner'),
            ('パン','pan','bread'),
            ('みず','mizu','water'),
            ('おちゃ','ocha','green tea'),
            ('コーヒー','koohii','coffee'),
            ('ビール','biiru','beer'),
            ('おさけ','osake','sake / alcohol'),
            ('ぎゅうにゅう / ミルク','gyuunyuu / miruku','milk'),
            ('ジュース','juusu','juice'),
            ('ワイン','wain','wine'),
            ('くだもの','kudamono','fruit'),
            ('やさい','yasai','vegetables'),
            ('にく','niku','meat'),
            ('さかな','sakana','fish'),
            ('たまご','tamago','egg'),
            ('チーズ','chiizu','cheese'),
            ('バター','bataa','butter'),
            ('ピザ','piza','pizza'),
            ('ケーキ','keeki','cake'),
            ('アイスクリーム','aisukuriimu','ice cream'),
            ('すし','sushi','sushi'),
            ('ラーメン','raamen','ramen'),
            ('うどん','udon','udon noodles'),
            ('そば','soba','soba noodles'),
            ('てんぷら','tenpura','tempura'),
            ('カレー','karee','curry'),
        ]},
        {'type': 'h3', 'text': 'Verbs (ます-form)'},
        {'type': 'vocab', 'rows': [
            ('いきます','ikimasu','to go'),
            ('きます','kimasu','to come'),
            ('かえります','kaerimasu','to return home'),
            ('たべます','tabemasu','to eat'),
            ('のみます','nomimasu','to drink'),
            ('みます','mimasu','to see / watch'),
            ('よみます','yomimasu','to read'),
            ('かきます','kakimasu','to write'),
            ('ききます','kikimasu','to listen / ask'),
            ('はなします','hanashimasu','to speak'),
            ('かいます','kaimasu','to buy'),
            ('うります','urimasu','to sell'),
            ('つくります','tsukurimasu','to make'),
            ('あいます','aimasu','to meet'),
            ('まちます','machimasu','to wait'),
            ('します','shimasu','to do'),
            ('あるきます','arukimasu','to walk'),
            ('はしります','hashirimasu','to run'),
            ('およぎます','oyogimasu','to swim'),
            ('ねます','nemasu','to sleep'),
            ('おきます','okimasu','to wake up'),
            ('はたらきます','hatarakimasu','to work'),
            ('やすみます','yasumimasu','to rest'),
            ('べんきょうします','benkyou shimasu','to study'),
            ('おしえます','oshiemasu','to teach'),
            ('おぼえます','oboemasu','to remember'),
            ('わすれます','wasuremasu','to forget'),
            ('わかります','wakarimasu','to understand'),
            ('あります','arimasu','to exist (inanimate)'),
            ('います','imasu','to exist (animate) / to be present'),
            ('すみます','sumimasu','to live / reside'),
        ]},
        {'type': 'h3', 'text': 'い-adjectives'},
        {'type': 'vocab', 'rows': [
            ('おおきい','ookii','big'),
            ('ちいさい','chiisai','small'),
            ('たかい','takai','tall / expensive / high'),
            ('やすい','yasui','cheap'),
            ('ひくい','hikui','low / short'),
            ('ながい','nagai','long'),
            ('みじかい','mijikai','short (length)'),
            ('あたらしい','atarashii','new'),
            ('ふるい','furui','old (of things)'),
            ('いい / よい','ii / yoi','good'),
            ('わるい','warui','bad'),
            ('おいしい','oishii','delicious'),
            ('まずい','mazui','bad-tasting'),
            ('あまい','amai','sweet'),
            ('からい','karai','spicy'),
            ('あつい','atsui','hot'),
            ('さむい','samui','cold (weather)'),
            ('つめたい','tsumetai','cold (to touch)'),
            ('あかるい','akarui','bright / cheerful'),
            ('くらい','kurai','dark'),
            ('はやい','hayai','fast / early'),
            ('おそい','osoi','slow / late'),
            ('むずかしい','muzukashii','difficult'),
            ('やさしい','yasashii','easy / kind'),
            ('おもしろい','omoshiroi','interesting / funny'),
            ('つまらない','tsumaranai','boring'),
            ('うれしい','ureshii','happy / glad'),
            ('かなしい','kanashii','sad'),
            ('いそがしい','isogashii','busy'),
            ('たのしい','tanoshii','enjoyable / fun'),
            ('かわいい','kawaii','cute'),
            ('うつくしい','utsukushii','beautiful'),
        ]},
        {'type': 'h3', 'text': 'な-adjectives'},
        {'type': 'vocab', 'rows': [
            ('きれい(な)','kirei (na)','pretty / clean'),
            ('しずか(な)','shizuka (na)','quiet'),
            ('にぎやか(な)','nigiyaka (na)','lively / bustling'),
            ('ゆうめい(な)','yuumei (na)','famous'),
            ('しんせつ(な)','shinsetsu (na)','kind'),
            ('げんき(な)','genki (na)','healthy / energetic'),
            ('ひま(な)','hima (na)','free (time)'),
            ('べんり(な)','benri (na)','convenient'),
            ('ふべん(な)','fuben (na)','inconvenient'),
            ('すき(な)','suki (na)','liked / favourite'),
            ('きらい(な)','kirai (na)','disliked'),
            ('じょうず(な)','jouzu (na)','skilled at'),
            ('へた(な)','heta (na)','unskilled at'),
            ('たいせつ(な)','taisetsu (na)','important'),
            ('しんぱい(な)','shinpai (na)','worried'),
            ('ざんねん(な)','zannen (na)','regrettable / too bad'),
        ]},
        {'type': 'h3', 'text': 'Numbers & counters'},
        {'type': 'vocab', 'rows': [
            ('いち、に、さん、よん、ご','ichi, ni, san, yon, go','1–5'),
            ('ろく、なな、はち、きゅう、じゅう','roku, nana, hachi, kyuu, juu','6–10'),
            ('ひゃく、せん、まん','hyaku, sen, man','100, 1,000, 10,000'),
            ('ひとつ、ふたつ、みっつ','hitotsu, futatsu, mittsu','1 thing, 2 things, 3 things'),
            ('ひとり、ふたり、さんにん','hitori, futari, san-nin','1 person, 2 people, 3 people'),
            ('いちまい、にまい','ichi-mai, ni-mai','1 flat thing, 2 flat things'),
            ('いっぽん、にほん','ippon, ni-hon','1 long thing, 2 long things'),
            ('いっぴき、にひき','ippiki, ni-hiki','1 small animal, 2 small animals'),
            ('いっこ、にこ','ikko, ni-ko','1 round thing, 2 round things'),
            ('いちじ、にじ','ichi-ji, ni-ji','1 o&rsquo;clock, 2 o&rsquo;clock'),
            ('いっぷん、にふん','ippun, ni-fun','1 minute, 2 minutes'),
            ('いちじかん','ichi-jikan','one hour (duration)'),
        ]},
        {'type': 'h3', 'text': 'Time & dates'},
        {'type': 'vocab', 'rows': [
            ('きょう','kyou','today'),
            ('あした','ashita','tomorrow'),
            ('きのう','kinou','yesterday'),
            ('こんしゅう','konshuu','this week'),
            ('らいしゅう','raishuu','next week'),
            ('せんしゅう','senshuu','last week'),
            ('まいにち','mainichi','every day'),
            ('まいしゅう','maishuu','every week'),
            ('あさ','asa','morning'),
            ('ひる','hiru','noon / daytime'),
            ('ばん / よる','ban / yoru','evening / night'),
            ('ごぜん','gozen','AM'),
            ('ごご','gogo','PM'),
            ('はん','han','half (past)'),
            ('げつようび','getsu-youbi','Monday'),
            ('かようび','ka-youbi','Tuesday'),
            ('すいようび','sui-youbi','Wednesday'),
            ('もくようび','moku-youbi','Thursday'),
            ('きんようび','kin-youbi','Friday'),
            ('どようび','do-youbi','Saturday'),
            ('にちようび','nichi-youbi','Sunday'),
            ('しゅうまつ','shuumatsu','weekend'),
            ('いちがつ…じゅうにがつ','ichi-gatsu…juuni-gatsu','January…December'),
            ('ついたち','tsuitachi','the 1st'),
            ('ふつか、みっか、よっか','futsuka, mikka, yokka','2nd, 3rd, 4th'),
            ('はつか','hatsuka','the 20th'),
        ]},
        {'type': 'h3', 'text': 'Weather, nature & animals'},
        {'type': 'vocab', 'rows': [
            ('てんき','tenki','weather'),
            ('あめ','ame','rain'),
            ('ゆき','yuki','snow'),
            ('かぜ','kaze','wind'),
            ('くも','kumo','cloud'),
            ('はれ','hare','sunny / clear'),
            ('そら','sora','sky'),
            ('やま','yama','mountain'),
            ('かわ','kawa','river'),
            ('うみ','umi','sea'),
            ('はな','hana','flower'),
            ('き','ki','tree'),
            ('いぬ','inu','dog'),
            ('ねこ','neko','cat'),
            ('とり','tori','bird'),
            ('さかな','sakana','fish'),
            ('うま','uma','horse'),
            ('うし','ushi','cow'),
        ]},
        {'type': 'h3', 'text': 'Pronouns & question words'},
        {'type': 'vocab', 'rows': [
            ('これ、それ、あれ','kore, sore, are','this, that, that over there'),
            ('この〜、その〜、あの〜','kono~, sono~, ano~','this ~, that ~, that ~ over there'),
            ('どれ、どの〜','dore, dono~','which one / which ~'),
            ('ここ、そこ、あそこ','koko, soko, asoko','here, there, over there'),
            ('どこ','doko','where?'),
            ('いつ','itsu','when?'),
            ('だれ','dare','who?'),
            ('なに / なん','nani / nan','what?'),
            ('なぜ / どうして','naze / doushite','why?'),
            ('どう','dou','how?'),
            ('いくら','ikura','how much (money)?'),
            ('いくつ','ikutsu','how many? / how old?'),
            ('どんな','donna','what kind of?'),
        ]},
    ],
})
