# The 100 N5 kanji taught in weeks 11 and 12 — the single source for the week
# grids and the kanji appendix. Each entry: (glyph, meaning, readings — examples).

KANJI = [
    # 1–10
    ('一', 'one', 'ichi — 一つ (hitotsu)'),
    ('二', 'two', 'ni — 二人 (futari)'),
    ('三', 'three', 'san — 三月 (sangatsu)'),
    ('四', 'four', 'yon / shi — 四月 (shigatsu)'),
    ('五', 'five', 'go — 五時 (goji)'),
    ('六', 'six', 'roku — 六本 (roppon)'),
    ('七', 'seven', 'nana / shichi — 七時'),
    ('八', 'eight', 'hachi — 八月'),
    ('九', 'nine', 'kyuu / ku — 九時 (kuji), 九月 (kugatsu)'),
    ('十', 'ten', 'juu — 十人'),
    # 11–20
    ('日', 'day / sun', 'hi / nichi — 日曜日; 今日 (kyou) is a special reading'),
    ('月', 'moon / month', 'tsuki / getsu — 月曜日, 一月'),
    ('火', 'fire', 'hi / ka — 火曜日'),
    ('水', 'water', 'mizu / sui — 水曜日'),
    ('木', 'tree', 'ki / moku — 木曜日'),
    ('金', 'gold / money', 'kane / kin — 金曜日'),
    ('土', 'earth / soil', 'tsuchi / do — 土曜日'),
    ('曜', 'day of week', 'you — 曜日'),
    ('時', 'time / hour', 'toki / ji — 時間, 三時'),
    ('年', 'year', 'toshi / nen — 来年 (rainen)'),
    # 21–30
    ('人', 'person', 'hito / jin — 日本人, 一人'),
    ('男', 'man', 'otoko / dan — 男の人'),
    ('女', 'woman', 'onna / jo — 女の人'),
    ('子', 'child', 'ko / shi — 子ども'),
    ('父', 'father', 'chichi / fu — お父さん'),
    ('母', 'mother', 'haha / bo — お母さん'),
    ('友', 'friend', 'tomo / yuu — 友だち'),
    ('先', 'ahead / previous', 'saki / sen — 先生'),
    ('生', 'life / birth', 'iki / sei — 学生, 先生'),
    ('名', 'name', 'na / mei — 名前'),
    # 31–40
    ('大', 'big', 'oo / dai — 大学'),
    ('小', 'small', 'chii / shou — 小さい'),
    ('中', 'middle / inside', 'naka / chuu — 中国'),
    ('上', 'above / up', 'ue / jou — 上手'),
    ('下', 'below / down', 'shita / ka — 地下 (chika); also kuda- in 下さい'),
    ('前', 'before / in front', 'mae / zen — 名前'),
    ('後', 'after / behind', 'ushiro / go — 午後'),
    ('外', 'outside', 'soto / gai — 外国'),
    ('右', 'right side', 'migi / u — 右手'),
    ('左', 'left side', 'hidari / sa — 左手'),
    # 41–50
    ('口', 'mouth', 'kuchi / kou — 入口'),
    ('目', 'eye', 'me / moku — 目'),
    ('手', 'hand', 'te / shu — 右手, 上手'),
    ('足', 'foot / leg', 'ashi / soku'),
    ('耳', 'ear', 'mimi / ji'),
    ('力', 'power / strength', 'chikara / ryoku'),
    ('山', 'mountain', 'yama / san — 富士山'),
    ('川', 'river', 'kawa / sen'),
    ('田', 'rice field', 'ta / den — 田中'),
    ('円', 'yen / circle', 'en — 千円'),
    # 51–60
    ('行', 'to go', 'iku / kou — 行きます'),
    ('来', 'to come', 'kuru / rai — 来週'),
    ('食', 'to eat', 'taberu / shoku — 食事'),
    ('飲', 'to drink', 'nomu / in — 飲み物'),
    ('見', 'to see', 'miru / ken — 見ます'),
    ('聞', 'to hear / ask', 'kiku / bun — 新聞'),
    ('読', 'to read', 'yomu / doku — 読みます'),
    ('書', 'to write', 'kaku / sho — 書きます'),
    ('話', 'to speak', 'hanasu / wa — 話します, 電話'),
    ('買', 'to buy', 'kau / bai — 買います'),
    # 61–70
    ('家', 'house / home', 'ie / ka — 家族'),
    ('店', 'shop', 'mise / ten — お店'),
    ('駅', 'station', 'eki — 東京駅'),
    ('道', 'road / way', 'michi / dou — 道路'),
    ('町', 'town', 'machi / chou'),
    ('市', 'city', 'ichi / shi — 市場'),
    ('国', 'country', 'kuni / koku — 外国人'),
    ('車', 'car / vehicle', 'kuruma / sha — 電車'),
    ('電', 'electricity', 'den — 電話, 電車'),
    ('気', 'spirit / air', 'ki — 元気'),
    # 71–80
    ('花', 'flower', 'hana / ka'),
    ('空', 'sky', 'sora / kuu — 空港'),
    ('雨', 'rain', 'ame / u'),
    ('天', 'heaven / weather', 'ten — 天気'),
    ('魚', 'fish', 'sakana / gyo'),
    ('犬', 'dog', 'inu / ken'),
    ('入', 'enter', 'hairu / iru / nyuu — 入ります (hairimasu), 入口 (iriguchi)'),
    ('出', 'exit', 'deru / shutsu — 出口'),
    ('休', 'rest', 'yasumu / kyuu — 休みます'),
    ('立', 'stand', 'tatsu / ritsu — 立ちます'),
    # 81–90
    ('学', 'to learn', 'manabu / gaku — 学生, 大学'),
    ('校', 'school', 'kou — 学校'),
    ('高', 'high / expensive', 'takai / kou — 高校'),
    ('英', 'English', 'ei — 英語'),
    ('語', 'language', 'kataru / go — 日本語, 英語'),
    ('本', 'book / origin', 'hon / moto — 本, 日本'),
    ('文', 'sentence / writing', 'bun — 文学'),
    ('字', 'character / letter', 'ji — 漢字'),
    ('今', 'now', 'ima / kon — 今日, 今週'),
    ('半', 'half', 'han — 三時半'),
    # 91–100
    ('何', 'what', 'nani / nan — 何ですか'),
    ('百', 'hundred', 'hyaku — 三百'),
    ('千', 'thousand', 'sen — 千円'),
    ('万', 'ten thousand', 'man — 一万円'),
    ('午', 'noon / midday', 'go — 午前, 午後'),
    ('朝', 'morning', 'asa / chou — 朝ごはん'),
    ('昼', 'noon / daytime', 'hiru / chuu — 昼ごはん'),
    ('夜', 'night', 'yoru / ya'),
    ('新', 'new', 'atara / shin — 新しい, 新聞'),
    ('長', 'long / chief', 'naga / chou — 社長'),
]
