# All 12 weeks of course content, structured for the interactive HTML renderer.
# Ported one-to-one from the PDF course source files.

WEEKS = []

# ============================== WEEK 1 ==============================
WEEKS.append({
    'num': 1,
    'title': 'Hiragana: Part 1',
    'goals': [
        'Learn the first 25 hiragana (a, ka, sa, ta, na rows).',
        'Write each by hand with correct stroke order.',
        'Read your first simple Japanese words.',
        'Say and recognise basic greetings.',
    ],
    'sections': [
        {'type': 'h2', 'text': 'About hiragana'},
        {'type': 'p', 'text': 'Japanese uses three scripts: <b>hiragana</b> (ひらがな), <b>katakana</b> (カタカナ), and <b>kanji</b> (漢字). Hiragana is the native phonetic script — 46 basic characters, each representing one sound (a syllable, really). Every Japanese child learns hiragana first, and so will you. Every single thing in weeks 2–12 assumes it.'},
        {'type': 'h3', 'text': 'The first 25 hiragana'},
        {'type': 'kana', 'rows': [
            [('あ','a'),('い','i'),('う','u'),('え','e'),('お','o')],
            [('か','ka'),('き','ki'),('く','ku'),('け','ke'),('こ','ko')],
            [('さ','sa'),('し','shi'),('す','su'),('せ','se'),('そ','so')],
            [('た','ta'),('ち','chi'),('つ','tsu'),('て','te'),('と','to')],
            [('な','na'),('に','ni'),('ぬ','nu'),('ね','ne'),('の','no')],
        ]},
        {'type': 'p', 'text': '<b>Pronunciation notes.</b> Vowels are pure and short: <i>a</i> as in &ldquo;father&rdquo;, <i>i</i> as in &ldquo;ski&rdquo;, <i>u</i> as in &ldquo;flu&rdquo; (lips relaxed, not rounded), <i>e</i> as in &ldquo;red&rdquo;, <i>o</i> as in &ldquo;go&rdquo;. The order <b>a-i-u-e-o</b> is sacred — memorise it; it drives everything from dictionaries to verb conjugation.'},
        {'type': 'grammar', 'title': 'Writing by hand matters',
         'body': 'Each kana has a correct stroke order. It feels pedantic, but writing in the proper order burns the shape into memory far better than tracing. Use <b>kakimashou.com</b> or any stroke-order chart for the first week. Spend 10 minutes a day on just this.'},
        {'type': 'vocab', 'title': 'Reading practice — real words', 'rows': [
            ('あお','ao','blue'),
            ('いえ','ie','house'),
            ('うえ','ue','above / on top'),
            ('した','shita','below / under'),
            ('いけ','ike','pond'),
            ('かお','kao','face'),
            ('きく','kiku','to listen / to ask'),
            ('くに','kuni','country'),
            ('ねこ','neko','cat'),
            ('いぬ','inu','dog'),
            ('さけ','sake','sake / alcohol'),
            ('すし','sushi','sushi'),
            ('そと','soto','outside'),
            ('ちかい','chikai','close / near'),
            ('なつ','natsu','summer'),
        ]},
        {'type': 'vocab', 'title': 'Essential greetings', 'rows': [
            ('おはよう','ohayou','Good morning (casual)'),
            ('おはようございます','ohayou gozaimasu','Good morning (polite)'),
            ('こんにちは','konnichiwa','Hello / Good afternoon'),
            ('こんばんは','konbanwa','Good evening'),
            ('おやすみなさい','oyasumi nasai','Good night'),
            ('さようなら','sayounara','Goodbye'),
            ('ありがとう','arigatou','Thank you'),
            ('ありがとうございます','arigatou gozaimasu','Thank you (polite)'),
            ('すみません','sumimasen','Excuse me / Sorry'),
            ('はい','hai','Yes'),
            ('いいえ','iie','No'),
        ]},
        {'type': 'p', 'text': '<b>A quirk worth noting:</b> こんにちは and こんばんは end in は, pronounced <i>wa</i> here (not <i>ha</i>). This is because は was historically the topic particle (we meet it formally in week 5). Just memorise them.'},
        {'type': 'exercise', 'title': 'Exercises — Week 1', 'items': [
            'Write each of the 25 hiragana five times by hand, in order (a-i-u-e-o, ka-ki-ku-ke-ko …).',
            'Read these aloud and write the romaji: <span class="inline-jp">あき、くち、いし、せかい、たて、おとこ、かきね、ねつ</span>.',
            'Translate to hiragana (no kanji yet): <i>neko, inu, ue, shita, sushi, kao</i>.',
            'Greet an imaginary person in Japanese four times through the day — morning, afternoon, evening, night.',
            'Set up Anki or Renshuu and start a hiragana deck. Drill 10 minutes daily.',
        ]},
        {'type': 'resource', 'items': [
            '<b>Tofugu — Learn Hiragana</b> (free guide with mnemonics): tofugu.com/japanese/learn-hiragana',
            '<b>JapanesePod101 — Hiragana Lessons</b> on YouTube (short, 2–3 min each).',
            '<b>Kakimashou.com</b> for stroke-order practice in your browser.',
            'Anki deck: <i>Japanese Hiragana &amp; Katakana</i> (search in AnkiWeb shared decks).',
        ]},
        {'type': 'selfcheck', 'title': 'Self-check before Week 2', 'items': [
            'Can I read all 25 kana aloud, without looking at romaji, in under 60 seconds?',
            'Can I write あいうえお、かきくけこ etc. from memory, correctly, in order?',
            'Can I say &ldquo;good morning&rdquo;, &ldquo;thank you&rdquo;, &ldquo;excuse me&rdquo; without hesitation?',
        ], 'note': 'If any answer is &ldquo;no&rdquo;, repeat this week before moving on.'},
    ],
})

# ============================== WEEK 2 ==============================
WEEKS.append({
    'num': 2,
    'title': 'Hiragana: Part 2 + Dakuten + Combos',
    'goals': [
        'Learn the remaining hiragana (ha, ma, ya, ra, wa, n rows).',
        'Learn dakuten (゛) and handakuten (゜) — the voiced variants.',
        'Learn combo kana (きゃ, しゅ, etc.) and double consonants (っ).',
        'Read any hiragana word by the end of the week.',
    ],
    'sections': [
        {'type': 'h3', 'text': 'The remaining 21 base hiragana'},
        {'type': 'kana', 'rows': [
            [('は','ha'),('ひ','hi'),('ふ','fu'),('へ','he'),('ほ','ho')],
            [('ま','ma'),('み','mi'),('む','mu'),('め','me'),('も','mo')],
            [('や','ya'),None,('ゆ','yu'),None,('よ','yo')],
            [('ら','ra'),('り','ri'),('る','ru'),('れ','re'),('ろ','ro')],
            [('わ','wa'),None,None,None,('を','wo/o')],
            [('ん','n'),None,None,None,None],
        ]},
        {'type': 'p', 'text': 'A few notes: <b>ふ</b> is halfway between <i>fu</i> and <i>hu</i> — lips relaxed, almost blown. <b>を</b> is used only as a grammatical particle (we meet it week 6), pronounced <i>o</i>. <b>ん</b> is the only kana that stands alone as a consonant.'},
        {'type': 'h3', 'text': 'Dakuten (゛) and handakuten (゜) — voiced sounds'},
        {'type': 'p', 'text': 'Adding a dakuten mark changes an unvoiced consonant to its voiced partner: か→が (ka→ga), さ→ざ (sa→za), た→だ (ta→da), は→ば (ha→ba). The handakuten (small circle) applies only to the は-row: は→ぱ (ha→pa).'},
        {'type': 'kana', 'rows': [
            [('が','ga'),('ぎ','gi'),('ぐ','gu'),('げ','ge'),('ご','go')],
            [('ざ','za'),('じ','ji'),('ず','zu'),('ぜ','ze'),('ぞ','zo')],
            [('だ','da'),('ぢ','ji'),('づ','zu'),('で','de'),('ど','do')],
            [('ば','ba'),('び','bi'),('ぶ','bu'),('べ','be'),('ぼ','bo')],
            [('ぱ','pa'),('ぴ','pi'),('ぷ','pu'),('ぺ','pe'),('ぽ','po')],
        ]},
        {'type': 'h3', 'text': 'Combo kana (yōon)'},
        {'type': 'p', 'text': 'When a small や, ゆ, or よ follows an <i>i</i>-row kana (き, し, ち, に, ひ, み, り, ぎ, じ, び, ぴ), they merge into one syllable: き+ゃ = きゃ (<i>kya</i>, not <i>kiya</i>). Common examples:'},
        {'type': 'vocab', 'rows': [
            ('きゃく','kyaku','guest'),
            ('しゃしん','shashin','photograph'),
            ('ちゃいろ','chairo','brown colour'),
            ('ひゃく','hyaku','hundred'),
            ('りょこう','ryokou','travel / trip'),
            ('じゅう','juu','ten'),
            ('しゅみ','shumi','hobby'),
        ]},
        {'type': 'grammar', 'title': 'The small っ (sokuon) and long vowels',
         'body': 'A small <b>っ</b> doubles the following consonant: <b>がっこう</b> is pronounced <i>gakkou</i>, with a tiny pause. Long vowels are shown by adding another vowel kana: <b>おかあさん</b> (<i>okaasan</i>, mother) — long &ldquo;a&rdquo;. <b>おにいさん</b> (<i>oniisan</i>, older brother) — long &ldquo;i&rdquo;. An exception: long <i>o</i> is usually written with <b>う</b>: <b>とうきょう</b> (<i>Toukyou</i>).'},
        {'type': 'vocab', 'title': 'Reading practice', 'rows': [
            ('はな','hana','flower / nose'),
            ('みず','mizu','water'),
            ('やま','yama','mountain'),
            ('ゆき','yuki','snow'),
            ('よる','yoru','night'),
            ('ほん','hon','book'),
            ('えん','en','yen (currency)'),
            ('ともだち','tomodachi','friend'),
            ('がっこう','gakkou','school'),
            ('せんせい','sensei','teacher'),
            ('でんわ','denwa','telephone'),
            ('かぞく','kazoku','family'),
            ('じかん','jikan','time'),
            ('しんぶん','shinbun','newspaper'),
            ('おちゃ','ocha','tea'),
        ]},
        {'type': 'exercise', 'title': 'Exercises — Week 2', 'items': [
            'Write the full hiragana chart from memory (all 46 base kana).',
            'Transcribe to romaji: <span class="inline-jp">がくせい、びょういん、きょう、しゅくだい、りんご、ぜんぶ、ぎゅうにゅう、しゃちょう</span>.',
            'Write in hiragana: <i>tomodachi, denwa, gakkou, sensei, mizu, hana, yuki, juu, hyaku</i>.',
            'Read aloud three times: <span class="inline-jp">きのう、ともだちと、こうえんで、しゃしんを、とりました。</span>',
            'Can you read a line of hiragana in a children&rsquo;s book? Try one.',
        ]},
        {'type': 'resource', 'items': [
            '<b>Tofugu — Dakuten and Combo Hiragana</b>: tofugu.com/japanese/dakuten-handakuten',
            '<b>Dr. Moku Hiragana</b> app — mnemonic-based, free trial.',
            '<b>Real Kana</b> (realkana.com) — bare-bones drill site. Set it to full hiragana and grind.',
        ]},
        {'type': 'selfcheck', 'title': 'Self-check before Week 3', 'items': [
            'Can I read any hiragana word, even unfamiliar ones, aloud?',
            'Do I understand the difference between <b>きよ</b> (kiyo) and <b>きょ</b> (kyo)?',
            'Can I write the full hiragana chart from memory in under five minutes?',
        ]},
    ],
})

# ============================== WEEK 3 ==============================
WEEKS.append({
    'num': 3,
    'title': 'Katakana: The Loan-Word Script',
    'goals': [
        'Learn all 46 katakana + dakuten + combos.',
        'Understand when and why katakana is used.',
        'Read common loan words (gairaigo).',
        'Write your own name in katakana.',
    ],
    'sections': [
        {'type': 'h2', 'text': 'What is katakana for?'},
        {'type': 'p', 'text': 'Katakana is the same sound system as hiragana — 46 characters, same syllables — but with sharper, more angular shapes. It&rsquo;s used mainly for:'},
        {'type': 'ul', 'items': [
            '<b>Loan words</b> from English and other languages: コーヒー (<i>koohii</i>, coffee), コンピューター (<i>konpyuutaa</i>, computer).',
            '<b>Foreign names</b>: your name is written in katakana when it&rsquo;s not Japanese.',
            '<b>Scientific names</b> for animals and plants.',
            '<b>Emphasis</b>, somewhat like italics in English.',
            '<b>Onomatopoeia</b>, especially sharp or mechanical sounds.',
        ]},
        {'type': 'h3', 'text': 'The full katakana chart'},
        {'type': 'kana', 'rows': [
            [('ア','a'),('イ','i'),('ウ','u'),('エ','e'),('オ','o')],
            [('カ','ka'),('キ','ki'),('ク','ku'),('ケ','ke'),('コ','ko')],
            [('サ','sa'),('シ','shi'),('ス','su'),('セ','se'),('ソ','so')],
            [('タ','ta'),('チ','chi'),('ツ','tsu'),('テ','te'),('ト','to')],
            [('ナ','na'),('ニ','ni'),('ヌ','nu'),('ネ','ne'),('ノ','no')],
            [('ハ','ha'),('ヒ','hi'),('フ','fu'),('ヘ','he'),('ホ','ho')],
            [('マ','ma'),('ミ','mi'),('ム','mu'),('メ','me'),('モ','mo')],
            [('ヤ','ya'),None,('ユ','yu'),None,('ヨ','yo')],
            [('ラ','ra'),('リ','ri'),('ル','ru'),('レ','re'),('ロ','ro')],
            [('ワ','wa'),None,None,None,('ヲ','wo')],
            [('ン','n'),None,None,None,None],
        ]},
        {'type': 'grammar', 'title': 'The long vowel mark — ー',
         'body': 'Katakana marks a long vowel with a dash <b>ー</b> (never by repeating the vowel). <b>コーヒー</b> is <i>koohii</i>, <b>ケーキ</b> is <i>keeki</i> (cake), <b>ビール</b> is <i>biiru</i> (beer). Written horizontally the mark is horizontal; vertically it becomes vertical.'},
        {'type': 'vocab', 'title': 'Loan words to practise', 'rows': [
            ('コーヒー','koohii','coffee'),
            ('ビール','biiru','beer'),
            ('パン','pan','bread'),
            ('ケーキ','keeki','cake'),
            ('アイスクリーム','aisukuriimu','ice cream'),
            ('チーズ','chiizu','cheese'),
            ('バター','bataa','butter'),
            ('コンピューター','konpyuutaa','computer'),
            ('テレビ','terebi','television'),
            ('カメラ','kamera','camera'),
            ('タクシー','takushii','taxi'),
            ('バス','basu','bus'),
            ('ホテル','hoteru','hotel'),
            ('レストラン','resutoran','restaurant'),
            ('アメリカ','amerika','America'),
            ('イギリス','igirisu','UK / England'),
            ('フランス','furansu','France'),
            ('スポーツ','supootsu','sport'),
            ('サッカー','sakkaa','football / soccer'),
            ('インターネット','intaanetto','internet'),
        ]},
        {'type': 'h3', 'text': 'Writing your own name'},
        {'type': 'p', 'text': 'Write your friend&rsquo;s name in katakana — this is one of the first things any Japanese learner does. The method: break the name into syllables, approximate each one with the nearest katakana, and use the long-vowel mark ー for drawn-out sounds. &ldquo;Smith&rdquo; = <b>スミス</b> (<i>sumisu</i>). &ldquo;Maria&rdquo; = <b>マリア</b>. &ldquo;Chris&rdquo; = <b>クリス</b>. &ldquo;Alexander&rdquo; = <b>アレクサンダー</b>.'},
        {'type': 'exercise', 'title': 'Exercises — Week 3', 'items': [
            'Write the full katakana chart from memory.',
            'Decode these loan words to English: <span class="inline-jp">レモン、ピザ、サラダ、ワイン、スーパー、ニュース、プール、タワー、カード、ソファー</span>.',
            'Write your own name, your friend&rsquo;s name, and the name of a city you love — all in katakana.',
            'Which script is which? <span class="inline-jp">すし / スシ、ねこ / ネコ、コーヒー / こーひー</span> — which looks &ldquo;right&rdquo; to a Japanese reader? Why?',
            'Walk down any grocery store aisle and read the katakana on labels. Many will surprise you.',
        ]},
        {'type': 'resource', 'items': [
            '<b>Tofugu — Learn Katakana</b>: tofugu.com/japanese/learn-katakana',
            '<b>Real Kana</b> — switch to katakana mode.',
            '<b>Katakana Memory Hints</b> by Dr. Moku — mnemonic-based.',
        ]},
    ],
})

# ============================== WEEK 4 ==============================
WEEKS.append({
    'num': 4,
    'title': 'Pronunciation, Numbers, Self-Introduction',
    'goals': [
        'Nail the pitch, rhythm, and vowel length of Japanese.',
        'Count from 0 to 10,000.',
        'Introduce yourself: name, nationality, occupation.',
        'Ask simple questions about another person.',
    ],
    'sections': [
        {'type': 'h2', 'text': 'Pronunciation: three things that matter'},
        {'type': 'ul', 'items': [
            '<b>Vowel length is phonemic.</b> <i>Ojisan</i> (uncle) and <i>ojiisan</i> (grandfather) are different words. Give the long one twice the time of the short one.',
            '<b>Pitch, not stress.</b> Japanese has no English-style stress. Each syllable gets equal time, with a small pitch rise or fall. Flat and even beats loud and emphatic.',
            '<b>Mora, not syllable.</b> Japanese counts by <i>mora</i> — small timing units. <b>さっぽろ</b> (Sapporo) is four mora: <i>sa-(pause)-po-ro</i>. The small っ counts.',
        ]},
        {'type': 'vocab', 'title': 'Numbers 0–10', 'rows': [
            ('ゼロ / 零','zero / rei','0'),
            ('一','ichi','1'),
            ('二','ni','2'),
            ('三','san','3'),
            ('四','yon / shi','4'),
            ('五','go','5'),
            ('六','roku','6'),
            ('七','nana / shichi','7'),
            ('八','hachi','8'),
            ('九','kyuu / ku','9'),
            ('十','juu','10'),
        ]},
        {'type': 'p', 'text': '<b>Why two readings?</b> 四 (<i>shi</i>) and 七 (<i>shichi</i>) sound like &ldquo;death&rdquo; and are often avoided; most people prefer <i>yon</i> and <i>nana</i> in daily life. 九 is <i>kyuu</i> except in a few compound expressions.'},
        {'type': 'h3', 'text': '11–100 and beyond'},
        {'type': 'p', 'text': 'Numbers are additive and transparent: 11 is 十一 (<i>juu-ichi</i>, &ldquo;ten-one&rdquo;). 20 is 二十 (<i>ni-juu</i>, &ldquo;two-ten&rdquo;). 35 is 三十五 (<i>san-juu-go</i>, &ldquo;three-ten-five&rdquo;). 100 is 百 (<i>hyaku</i>). 1000 is 千 (<i>sen</i>). 10,000 is 万 (<i>man</i>) — note that Japanese groups by ten-thousands, not thousands. So 50,000 is 五万 (<i>go-man</i>), not &ldquo;fifty thousand.&rdquo;'},
        {'type': 'vocab', 'rows': [
            ('二十','nijuu','20'),
            ('三十','sanjuu','30'),
            ('百','hyaku','100'),
            ('二百','nihyaku','200'),
            ('三百','sanbyaku','300 (sound change!)'),
            ('六百','roppyaku','600 (sound change!)'),
            ('八百','happyaku','800 (sound change!)'),
            ('千','sen','1,000'),
            ('三千','sanzen','3,000 (sound change!)'),
            ('八千','hassen','8,000 (sound change!)'),
            ('一万','ichiman','10,000'),
        ]},
        {'type': 'p', 'text': '<b>Sound changes.</b> Numbers mutate before h-sounds: <i>san-hyaku</i> becomes <i>sanbyaku</i>, <i>roku-hyaku</i> becomes <i>roppyaku</i>. These feel maddening at first but become automatic. Say them aloud rather than memorising rules.'},
        {'type': 'grammar', 'title': 'はじめまして (hajimemashite)',
         'body': 'The ritual opening of a first-time introduction. Literally &ldquo;for the first time&rdquo;.<br><br><b>Template:</b><br><span class="inline-jp">はじめまして。</span> &nbsp; <i>Hajimemashite.</i> &nbsp; (Nice to meet you.)<br><span class="inline-jp">わたしは [name] です。</span> &nbsp; <i>Watashi wa [name] desu.</i> &nbsp; (I am [name].)<br><span class="inline-jp">[country] から きました。</span> &nbsp; <i>[country] kara kimashita.</i> &nbsp; (I come from [country].)<br><span class="inline-jp">[job] です。</span> &nbsp; <i>[job] desu.</i> &nbsp; (I am a [job].)<br><span class="inline-jp">どうぞ よろしく おねがいします。</span> &nbsp; <i>Douzo yoroshiku onegaishimasu.</i> &nbsp; (Please treat me well.)'},
        {'type': 'vocab', 'title': 'Nationalities, occupations, basics', 'rows': [
            ('わたし','watashi','I / me'),
            ('あなた','anata','you (use sparingly)'),
            ('アメリカ人','amerika-jin','American'),
            ('日本人 / にほんじん','nihon-jin','Japanese person'),
            ('イギリス人','igirisu-jin','British person'),
            ('学生 / がくせい','gakusei','student'),
            ('会社員 / かいしゃいん','kaishain','office worker'),
            ('先生 / せんせい','sensei','teacher'),
            ('医者 / いしゃ','isha','doctor'),
            ('エンジニア','enjinia','engineer'),
            ('コック / 料理人','kokku / ryourinin','cook'),
            ('なまえ','namae','name'),
            ('おなまえは？','onamae wa?','What&rsquo;s your name?'),
            ('何歳 / なんさい','nansai','how old?'),
            ('どこから','doko kara','from where?'),
        ]},
        {'type': 'exercise', 'title': 'Exercises — Week 4', 'items': [
            'Write out your own self-introduction (name, country, job) in hiragana + katakana. Memorise it.',
            'Count aloud from 1 to 30, then by tens to 100, then by hundreds to 1,000.',
            'Translate: &ldquo;I am a student. I come from the US. Nice to meet you.&rdquo;',
            'Someone says <span class="inline-jp">おなまえは？</span> — write your answer.',
            'How do you say these prices? 350円, 1,200円, 8,800円, 25,000円.',
        ]},
        {'type': 'resource', 'items': [
            '<b>JapanesePod101 — Introducing Yourself in Japanese</b> on YouTube (~5 minutes).',
            '<b>Tofugu — Japanese Numbers</b>: tofugu.com/japanese/japanese-numbers',
            '<b>Nihongo con Teppei (Beginner)</b> — Episode 1 is a self-introduction in slow Japanese.',
        ]},
        {'type': 'selfcheck', 'title': 'Self-check before Week 5', 'items': [
            'Can I introduce myself for 20 seconds without stopping?',
            'Can I count to 100 without using fingers?',
            'Can I say prices in yen for anything up to 10,000?',
        ]},
    ],
})

# ============================== WEEK 5 ==============================
WEEKS.append({
    'num': 5,
    'title': 'Sentence Structure & Particles は, が, か',
    'goals': [
        'Understand Japanese word order: topic + comment.',
        'Use the topic particle は correctly.',
        'Form yes/no questions with か.',
        'Distinguish は from が (the single most-asked beginner question).',
    ],
    'sections': [
        {'type': 'h2', 'text': 'How a Japanese sentence is built'},
        {'type': 'p', 'text': 'Japanese is a <b>Subject-Object-Verb</b> language — the verb comes last. More importantly, Japanese is a <b>topic-prominent</b> language: the first thing you often announce is not the subject but the <i>topic</i> — &ldquo;as for X…&rdquo; — and then say something about it.'},
        {'type': 'p', 'text': '<span class="inline-jp">わたし は がくせい です。</span> &nbsp; <i>Watashi wa gakusei desu.</i><br>Literally: &ldquo;As for me, student am.&rdquo; &nbsp; → &nbsp; &ldquo;I am a student.&rdquo;'},
        {'type': 'grammar', 'title': 'The topic particle は',
         'body': 'The particle <b>は</b> marks the topic of the sentence — what we&rsquo;re talking about. It&rsquo;s written with the kana for <i>ha</i> but <b>pronounced <i>wa</i></b> when used as a particle. This is a historical quirk; just remember it.<br><br><b>Pattern:</b> &nbsp;&nbsp; [topic] + は + [description] + です。<br><span class="inline-jp">これ は ほん です。</span> &nbsp; <i>Kore wa hon desu.</i> &nbsp; (This is a book.)<br><span class="inline-jp">わたし は にほんじん じゃないです。</span> &nbsp; <i>Watashi wa nihonjin ja nai desu.</i> &nbsp; (I am not Japanese.)'},
        {'type': 'h2', 'text': 'です and its negative'},
        {'type': 'p', 'text': '<b>です</b> is the copula — it functions like &ldquo;is / am / are&rdquo; and makes a sentence polite. It never conjugates for person or number.'},
        {'type': 'vocab', 'rows': [
            ('です','desu','is / am / are (polite)'),
            ('じゃないです','ja nai desu','is not (polite, casual)'),
            ('ではありません','dewa arimasen','is not (polite, formal)'),
            ('でした','deshita','was / were'),
            ('じゃなかったです','ja nakatta desu','was not'),
        ]},
        {'type': 'grammar', 'title': 'Yes/no questions with か',
         'body': 'Attach <b>か</b> to the end of a statement to turn it into a question. The word order does not change. In writing, Japanese typically omits the question mark.<br><br><span class="inline-jp">あなた は がくせい です か。</span> &nbsp; <i>Anata wa gakusei desu ka.</i> &nbsp; (Are you a student?)<br><span class="inline-jp">はい、がくせい です。</span> &nbsp; <i>Hai, gakusei desu.</i> &nbsp; (Yes, I am.)<br><span class="inline-jp">いいえ、がくせい じゃないです。</span> &nbsp; <i>Iie, gakusei ja nai desu.</i> &nbsp; (No, I&rsquo;m not.)'},
        {'type': 'h2', 'text': 'は vs が — the beginner&rsquo;s classic question'},
        {'type': 'p', 'text': 'Both particles can look like &ldquo;the subject marker&rdquo; from English, but they do different work:'},
        {'type': 'ul', 'items': [
            '<b>は</b> marks the <i>topic</i> — information we are already discussing or taking for granted. It often has an implicit &ldquo;as for&rdquo; or &ldquo;speaking of&rdquo; sense.',
            '<b>が</b> marks the <i>subject</i>, especially when it&rsquo;s new information, when answering &ldquo;who/what?&rdquo;, or when the subject is in focus.',
        ]},
        {'type': 'p', 'text': '<span class="inline-jp">ねこ は かわいい です。</span> &nbsp; (Cats are cute.) → <i>general statement about cats.</i><br><span class="inline-jp">ねこ が います。</span> &nbsp; (There is a cat.) → <i>new information; the cat is the focus.</i><br><br><b>Rule of thumb for now:</b> use は for self-introductions, descriptions, and general statements. Use が when answering &ldquo;who?&rdquo; or &ldquo;what?&rdquo; and in a few specific constructions you&rsquo;ll meet gradually. Perfect feel for this takes months — don&rsquo;t rush it.'},
        {'type': 'vocab', 'title': 'These / those / what', 'rows': [
            ('これ','kore','this (near me)'),
            ('それ','sore','that (near you)'),
            ('あれ','are','that over there'),
            ('どれ','dore','which?'),
            ('この [noun]','kono [noun]','this [noun]'),
            ('その [noun]','sono [noun]','that [noun]'),
            ('あの [noun]','ano [noun]','that [noun] over there'),
            ('どの [noun]','dono [noun]','which [noun]?'),
            ('なん / なに','nan / nani','what?'),
            ('だれ','dare','who?'),
        ]},
        {'type': 'vocab', 'title': 'Everyday vocabulary', 'rows': [
            ('本 / ほん','hon','book'),
            ('ペン','pen','pen'),
            ('かばん','kaban','bag'),
            ('つくえ','tsukue','desk'),
            ('いす','isu','chair'),
            ('しんぶん','shinbun','newspaper'),
            ('じしょ','jisho','dictionary'),
            ('うち / いえ','uchi / ie','home / house'),
            ('かいしゃ','kaisha','company'),
            ('えき','eki','train station'),
            ('みせ','mise','shop'),
        ]},
        {'type': 'exercise', 'title': 'Exercises — Week 5', 'items': [
            'Translate to Japanese: &ldquo;This is a book.&rdquo; &ldquo;That (over there) is a station.&rdquo; &ldquo;Is this your bag?&rdquo;',
            'Someone asks <span class="inline-jp">あのひとはだれですか。</span> How do you answer that it&rsquo;s a teacher?',
            'Make three sentences about things on your desk, using これ / それ / あれ.',
            'Rewrite in the negative: <span class="inline-jp">これはペンです。</span> &nbsp; <span class="inline-jp">あの人はせんせいです。</span>',
            'Think of three questions you&rsquo;d ask a new acquaintance. Write them in Japanese.',
        ]},
        {'type': 'resource', 'items': [
            '<b>Tae Kim — State-of-Being</b> and <b>Introduction to Particles</b> — guidetojapanese.org',
            '<b>Cure Dolly</b> on YouTube — her &ldquo;Japanese from Scratch&rdquo; series is quirky but exceptionally clear on は vs が.',
            '<b>JapanesePod101 — Essential Japanese Questions</b> playlist.',
        ]},
    ],
})

# ============================== WEEK 6 ==============================
WEEKS.append({
    'num': 6,
    'title': 'More Particles: を, に, で, へ, と, も',
    'goals': [
        'Mark direct objects with を.',
        'Say where you&rsquo;re going (に, へ), where you are (に), when (に), and where you do things (で).',
        'Say &ldquo;and&rdquo; with と, and &ldquo;also/too&rdquo; with も.',
        'Combine particles into real sentences.',
    ],
    'sections': [
        {'type': 'h2', 'text': 'Particles do what prepositions do in English'},
        {'type': 'p', 'text': 'In English, &ldquo;to&rdquo; and &ldquo;at&rdquo; and &ldquo;with&rdquo; come <i>before</i> the noun. In Japanese, particles come <i>after</i> the noun and define its role in the sentence. Think of them as little tags glued to each noun saying &ldquo;this is where it goes, this is when it happens, this is what got done to it.&rdquo;'},
        {'type': 'grammar', 'title': 'を — the direct object marker',
         'body': '<b>を</b> marks what the verb acts on. Written with the kana wo but pronounced <i>o</i>.<br><br><span class="inline-jp">パンをたべます。</span> &nbsp; <i>Pan o tabemasu.</i> &nbsp; (I eat bread.)<br><span class="inline-jp">ほんをよみます。</span> &nbsp; <i>Hon o yomimasu.</i> &nbsp; (I read a book.)<br><span class="inline-jp">みずをのみます。</span> &nbsp; <i>Mizu o nomimasu.</i> &nbsp; (I drink water.)'},
        {'type': 'grammar', 'title': 'に — destination, time, and location of existence',
         'body': '<b>に</b> has several uses — all involve a point in space or time.<br><br><b>Destination (going <i>to</i>):</b> <span class="inline-jp">がっこうにいきます。</span> &nbsp; <i>Gakkou ni ikimasu.</i> &nbsp; (I go to school.)<br><b>Specific time:</b> <span class="inline-jp">7じにおきます。</span> &nbsp; <i>Shichi-ji ni okimasu.</i> &nbsp; (I wake up at 7.)<br><b>Existence (location of a thing):</b> <span class="inline-jp">ねこはへやにいます。</span> &nbsp; (The cat is in the room.)<br><b>Indirect object (<i>to</i> someone):</b> <span class="inline-jp">ともだちにてがみをかきます。</span> &nbsp; (I write a letter to a friend.)'},
        {'type': 'grammar', 'title': 'で — where an action happens, and the means',
         'body': '<b>で</b> marks the location where an action is performed (not where something simply exists), and the means or tool used.<br><br><b>Location of action:</b> <span class="inline-jp">カフェでコーヒーをのみます。</span> &nbsp; (I drink coffee at a café.)<br><b>Means (<i>by</i>):</b> <span class="inline-jp">バスでいきます。</span> &nbsp; (I go by bus.)<br><b>Material:</b> <span class="inline-jp">きでつくります。</span> &nbsp; (I make it from wood.)<br><br><b>Contrast with に:</b> に is for destination or location of existence; で is for the stage on which action happens.'},
        {'type': 'grammar', 'title': 'へ, と, も',
         'body': '<b>へ</b> — direction toward. Overlaps with に for destinations; a touch more literary. Pronounced <i>e</i>.<br><span class="inline-jp">とうきょうへいきます。</span> &nbsp; (I&rsquo;m going to Tokyo.)<br><br><b>と</b> — &ldquo;and&rdquo; between nouns, or &ldquo;with&rdquo; a person.<br><span class="inline-jp">パンとチーズをたべます。</span> &nbsp; (I eat bread and cheese.)<br><span class="inline-jp">ともだちといきます。</span> &nbsp; (I go with a friend.)<br><br><b>も</b> — &ldquo;also / too&rdquo;. Replaces は or が.<br><span class="inline-jp">わたしもがくせいです。</span> &nbsp; (I am also a student.)'},
        {'type': 'vocab', 'title': 'Vocabulary — verbs and places', 'rows': [
            ('いきます','ikimasu','to go'),
            ('きます','kimasu','to come'),
            ('かえります','kaerimasu','to return / go home'),
            ('たべます','tabemasu','to eat'),
            ('のみます','nomimasu','to drink'),
            ('みます','mimasu','to see / watch'),
            ('よみます','yomimasu','to read'),
            ('かきます','kakimasu','to write'),
            ('ききます','kikimasu','to listen / ask'),
            ('はなします','hanashimasu','to speak / talk'),
            ('かいます','kaimasu','to buy'),
            ('つくります','tsukurimasu','to make'),
            ('あいます','aimasu','to meet'),
            ('まちます','machimasu','to wait'),
            ('します','shimasu','to do'),
            ('カフェ','kafe','café'),
            ('こうえん','kouen','park'),
            ('びょういん','byouin','hospital'),
            ('ゆうびんきょく','yuubinkyoku','post office'),
            ('ぎんこう','ginkou','bank'),
            ('スーパー','suupaa','supermarket'),
        ]},
        {'type': 'exercise', 'title': 'Exercises — Week 6', 'items': [
            'Pick the right particle: <span class="inline-jp">ともだち___こうえん___いきます。</span> (two blanks)',
            'Translate: &ldquo;I buy bread at the supermarket.&rdquo;',
            'Translate: &ldquo;I eat sushi with my friend at a restaurant on Saturday.&rdquo;',
            'Which particle marks the <i>means</i> of travel? Make a sentence using it with &ldquo;bus&rdquo; or &ldquo;taxi.&rdquo;',
            'What&rsquo;s the difference between <span class="inline-jp">うちにいます</span> and <span class="inline-jp">うちでたべます</span>? Explain in your own words.',
        ]},
        {'type': 'resource', 'items': [
            '<b>Tae Kim — Particles Used with Verbs</b> — guidetojapanese.org',
            '<b>Japanese Ammo with Misa</b> on YouTube — her particle videos are long but hugely clarifying.',
            '<b>Marugoto Starter</b> (free online courses from the Japan Foundation) — real-life listening practice.',
        ]},
    ],
})

# ============================== WEEK 7 ==============================
WEEKS.append({
    'num': 7,
    'title': 'Verbs: The Three Groups and the ます-Form',
    'goals': [
        'Identify a verb&rsquo;s group — Godan, Ichidan, or Irregular.',
        'Conjugate any verb into its polite present/future form (~ます).',
        'Form the polite negative (~ません).',
        'Build full sentences describing routines.',
    ],
    'sections': [
        {'type': 'h2', 'text': 'Three verb groups'},
        {'type': 'p', 'text': 'Every Japanese verb falls into one of three groups. Which group it&rsquo;s in determines how you conjugate it. Beginners should learn the dictionary form and the group together.'},
        {'type': 'h3', 'text': 'Group 1 — Godan verbs (u-verbs)'},
        {'type': 'p', 'text': 'End in any <i>u</i>-row kana (<b>う, く, す, つ, ぬ, ぶ, む, る</b>). The most common group. To make the ます-form, change the final <i>u</i>-sound to the matching <i>i</i>-sound and add ます.'},
        {'type': 'vocab', 'rows': [
            ('かく','kaku','write → かきます (kakimasu)'),
            ('よむ','yomu','read → よみます'),
            ('のむ','nomu','drink → のみます'),
            ('はなす','hanasu','speak → はなします'),
            ('まつ','matsu','wait → まちます'),
            ('あう','au','meet → あいます'),
            ('かう','kau','buy → かいます'),
            ('いく','iku','go → いきます'),
            ('きく','kiku','listen → ききます'),
            ('あそぶ','asobu','play → あそびます'),
        ]},
        {'type': 'h3', 'text': 'Group 2 — Ichidan verbs (ru-verbs)'},
        {'type': 'p', 'text': 'End in <b>-iru</b> or <b>-eru</b>. To make the ます-form, drop the final る and add ます. This is the simpler, more regular group. A few verbs <i>look</i> like Group 2 but are actually Group 1 (<i>hairu</i>, <i>hashiru</i>, <i>kaeru</i> — return home); these you memorise individually.'},
        {'type': 'vocab', 'rows': [
            ('たべる','taberu','eat → たべます'),
            ('みる','miru','see → みます'),
            ('ねる','neru','sleep → ねます'),
            ('おきる','okiru','wake up → おきます'),
            ('あける','akeru','open → あけます'),
            ('しめる','shimeru','close → しめます'),
            ('でる','deru','exit → でます'),
            ('おしえる','oshieru','teach → おしえます'),
        ]},
        {'type': 'h3', 'text': 'Group 3 — Irregular (there are only two)'},
        {'type': 'p', 'text': 'Two verbs — the only true irregulars in the whole language.'},
        {'type': 'vocab', 'rows': [
            ('する','suru','do → します (shimasu)'),
            ('くる','kuru','come → きます (kimasu)'),
        ]},
        {'type': 'grammar', 'title': 'The ます-form: polite present and future',
         'body': 'The ~ます form is the polite present-and-future tense. It covers both &ldquo;I eat&rdquo; and &ldquo;I will eat&rdquo; — context tells you which. Use it with anyone you don&rsquo;t know well, teachers, strangers, in work settings. Among close friends, the casual (dictionary) form is used instead. For your first six months, stay polite.<br><br><b>Negative:</b> change ます to <b>ません</b>.<br><span class="inline-jp">たべます</span> → eats / will eat &nbsp;&nbsp; <span class="inline-jp">たべません</span> → does not eat<br><span class="inline-jp">いきます</span> → goes / will go &nbsp;&nbsp; <span class="inline-jp">いきません</span> → does not go'},
        {'type': 'h2', 'text': 'Putting it together'},
        {'type': 'p', 'text': '<span class="inline-jp">わたしは まいにち コーヒーを のみます。</span><br><i>Watashi wa mainichi koohii o nomimasu.</i> &nbsp; (I drink coffee every day.)<br><br><span class="inline-jp">あした ともだちと えいがを みます。</span><br><i>Ashita tomodachi to eiga o mimasu.</i> &nbsp; (Tomorrow I will watch a movie with a friend.)<br><br><span class="inline-jp">にちようびは はたらきません。</span><br><i>Nichiyoubi wa hatarakimasen.</i> &nbsp; (I don&rsquo;t work on Sundays.)'},
        {'type': 'vocab', 'title': 'Time-of-day vocabulary', 'rows': [
            ('まいにち','mainichi','every day'),
            ('きょう','kyou','today'),
            ('あした','ashita','tomorrow'),
            ('きのう','kinou','yesterday'),
            ('あさ','asa','morning'),
            ('ひる','hiru','noon / daytime'),
            ('よる','yoru','evening / night'),
            ('あさごはん','asagohan','breakfast'),
            ('ひるごはん','hirugohan','lunch'),
            ('ばんごはん','bangohan','dinner'),
            ('しごと','shigoto','work / job'),
            ('はたらく','hataraku','to work → はたらきます'),
            ('べんきょうする','benkyou suru','to study → べんきょうします'),
            ('うんどうする','undou suru','to exercise → うんどうします'),
        ]},
        {'type': 'exercise', 'title': 'Exercises — Week 7', 'items': [
            'Conjugate to the ます-form: かく、よむ、たべる、する、くる、はなす、みる、あそぶ.',
            'Translate: &ldquo;Every morning I drink coffee and read the newspaper.&rdquo;',
            'Translate: &ldquo;I don&rsquo;t eat breakfast on weekends.&rdquo;',
            'Write five sentences about your friend&rsquo;s typical day using at least five different verbs.',
            'Identify the group for each verb: かう、たべる、する、はたらく、おきる、まつ、くる、みる.',
        ]},
        {'type': 'resource', 'items': [
            '<b>Tae Kim — Polite Form and Verb Stems</b> — guidetojapanese.org',
            '<b>Japanese with Shun</b> podcast — slow Japanese using lots of ~ます forms.',
            '<b>Tofugu — Japanese Verb Conjugation</b> — tofugu.com/japanese/japanese-verb-conjugation',
        ]},
    ],
})

# ============================== WEEK 8 ==============================
WEEKS.append({
    'num': 8,
    'title': 'Past Tense & Adjectives',
    'goals': [
        'Form the polite past: ~ました / ~ませんでした.',
        'Use い-adjectives and な-adjectives correctly.',
        'Describe things in the present and the past.',
        'Modify nouns with adjectives (big dog, quiet room).',
    ],
    'sections': [
        {'type': 'grammar', 'title': 'Polite past tense',
         'body': '<b>ました</b> replaces ます to mark completed action in the past.<br><b>ませんでした</b> replaces ません for the past negative.<br><br><span class="inline-jp">たべます</span> → <span class="inline-jp">たべました</span> &nbsp; (ate) &nbsp;&nbsp; <span class="inline-jp">たべませんでした</span> &nbsp; (did not eat)<br><span class="inline-jp">いきます</span> → <span class="inline-jp">いきました</span> &nbsp; (went) &nbsp;&nbsp; <span class="inline-jp">いきませんでした</span> &nbsp; (did not go)<br><span class="inline-jp">します</span> → <span class="inline-jp">しました</span> &nbsp;&nbsp; <span class="inline-jp">きます</span> → <span class="inline-jp">きました</span>'},
        {'type': 'h3', 'text': 'Example'},
        {'type': 'p', 'text': '<span class="inline-jp">きのう ともだちと レストランで ピザを たべました。</span><br><i>Kinou tomodachi to resutoran de piza o tabemashita.</i><br>(Yesterday I ate pizza with a friend at a restaurant.)'},
        {'type': 'h2', 'text': 'Adjectives: two types'},
        {'type': 'p', 'text': 'Japanese has two kinds of adjectives, and they conjugate differently. Memorise which group each one belongs to when you learn it.'},
        {'type': 'h3', 'text': 'い-adjectives'},
        {'type': 'p', 'text': 'End in <b>い</b> (not just い at the end — the whole word is adjectival, including the い). They conjugate for tense and negation on their own, without using です for grammar (though です is added for politeness).'},
        {'type': 'vocab', 'rows': [
            ('おおきい','ookii','big'),
            ('ちいさい','chiisai','small'),
            ('たかい','takai','expensive / tall / high'),
            ('やすい','yasui','cheap'),
            ('あたらしい','atarashii','new'),
            ('ふるい','furui','old (of things)'),
            ('いい / よい','ii / yoi','good'),
            ('わるい','warui','bad'),
            ('おいしい','oishii','delicious'),
            ('むずかしい','muzukashii','difficult'),
            ('やさしい','yasashii','easy / kind'),
            ('あつい','atsui','hot'),
            ('さむい','samui','cold (weather)'),
            ('いそがしい','isogashii','busy'),
        ]},
        {'type': 'grammar', 'title': 'い-adjective conjugation',
         'body': '<b>Present:</b> &nbsp;&nbsp; <span class="inline-jp">おいしい(です)</span> &nbsp; → delicious<br><b>Negative:</b> drop final い, add くない &nbsp;&nbsp; <span class="inline-jp">おいしくない(です)</span><br><b>Past:</b> drop final い, add かった &nbsp;&nbsp; <span class="inline-jp">おいしかった(です)</span><br><b>Past negative:</b> <span class="inline-jp">おいしくなかった(です)</span><br><br><b>Watch out:</b> いい (good) is irregular. It becomes よくない / よかった / よくなかった.'},
        {'type': 'h3', 'text': 'な-adjectives'},
        {'type': 'p', 'text': 'Grammatically behave more like nouns. They conjugate using <b>です</b> and attach <b>な</b> when directly modifying a noun. They do not themselves change for tense — です does the work.'},
        {'type': 'vocab', 'rows': [
            ('きれい','kirei','pretty / clean'),
            ('しずか','shizuka','quiet'),
            ('にぎやか','nigiyaka','lively / bustling'),
            ('ゆうめい','yuumei','famous'),
            ('しんせつ','shinsetsu','kind'),
            ('げんき','genki','healthy / energetic'),
            ('ひま','hima','free (time)'),
            ('べんり','benri','convenient'),
            ('すき','suki','liked / favourite'),
            ('きらい','kirai','disliked'),
            ('じょうず','jouzu','skilled / good at'),
            ('へた','heta','unskilled / bad at'),
        ]},
        {'type': 'p', 'text': '<b>Trap:</b> きれい ends in い but is actually a <b>な-adjective</b>. So is ゆうめい. The ending is a coincidence. Memorise these as exceptions.'},
        {'type': 'grammar', 'title': 'な-adjective conjugation',
         'body': '<b>Present:</b> <span class="inline-jp">しずかです</span> &nbsp; → is quiet<br><b>Negative:</b> <span class="inline-jp">しずかじゃないです</span> &nbsp; (or <span class="inline-jp">しずかではありません</span>)<br><b>Past:</b> <span class="inline-jp">しずかでした</span><br><b>Past negative:</b> <span class="inline-jp">しずかじゃなかったです</span>'},
        {'type': 'h2', 'text': 'Modifying a noun directly'},
        {'type': 'p', 'text': 'When an adjective sits in front of a noun to describe it:'},
        {'type': 'ul', 'items': [
            '<b>い-adjective:</b> just attach it. <span class="inline-jp">おおきい いぬ</span> (big dog), <span class="inline-jp">あたらしい ほん</span> (new book).',
            '<b>な-adjective:</b> add <b>な</b> between adjective and noun. <span class="inline-jp">しずかな へや</span> (quiet room), <span class="inline-jp">ゆうめいな ひと</span> (famous person).',
        ]},
        {'type': 'exercise', 'title': 'Exercises — Week 8', 'items': [
            'Rewrite in the past: <span class="inline-jp">たべます、いきます、します、よみます、かいます</span>.',
            'Rewrite in the past negative: <span class="inline-jp">ねます、はなします、きます</span>.',
            'Conjugate <span class="inline-jp">おいしい</span> in all four forms (present, neg, past, past neg).',
            'Conjugate <span class="inline-jp">きれい</span> in all four forms.',
            'Translate: &ldquo;Yesterday&rsquo;s dinner was delicious.&rdquo; &ldquo;This book is interesting.&rdquo; &ldquo;Her room is quiet.&rdquo;',
            'Describe three things you saw yesterday using an adjective + noun.',
        ]},
        {'type': 'resource', 'items': [
            '<b>Tae Kim — Adjectives</b> — guidetojapanese.org/learn/grammar/adjectives',
            '<b>Tofugu — Japanese Adjectives</b> — a thorough reference.',
            '<b>Comprehensible Japanese</b> on YouTube — adjective-heavy beginner videos.',
        ]},
    ],
})

# ============================== WEEK 9 ==============================
WEEKS.append({
    'num': 9,
    'title': 'The Te-form & Its Many Uses',
    'goals': [
        'Form the te-form from any verb (the trickiest conjugation in the course).',
        'Make polite requests: ~てください.',
        'Say what you&rsquo;re doing now: ~ています.',
        'Connect two actions in one sentence.',
    ],
    'sections': [
        {'type': 'h2', 'text': 'Why the te-form matters'},
        {'type': 'p', 'text': 'The te-form is the single most important conjugation in Japanese. It&rsquo;s a gateway form: on its own, it does nothing — it only exists to attach to other things. But those other things are everywhere: requests, progressive, permission, prohibition, giving/receiving actions. If you master only one conjugation, make it this one.'},
        {'type': 'h2', 'text': 'How to form it'},
        {'type': 'p', 'text': 'The rules differ by verb group. Group 2 is trivially easy; Group 1 is phonetic and takes a week to feel natural.'},
        {'type': 'h3', 'text': 'Group 2 (ichidan): drop る, add て'},
        {'type': 'p', 'text': '<span class="inline-jp">たべる</span> → <span class="inline-jp">たべて</span> &nbsp;&nbsp; <span class="inline-jp">みる</span> → <span class="inline-jp">みて</span> &nbsp;&nbsp; <span class="inline-jp">ねる</span> → <span class="inline-jp">ねて</span>'},
        {'type': 'h3', 'text': 'Group 3 (irregular)'},
        {'type': 'p', 'text': '<span class="inline-jp">する</span> → <span class="inline-jp">して</span> &nbsp;&nbsp; <span class="inline-jp">くる</span> → <span class="inline-jp">きて</span>'},
        {'type': 'h3', 'text': 'Group 1 (godan): depends on the final kana'},
        {'type': 'vocab', 'rows': [
            ('う, つ, る → って','u, tsu, ru → tte','あう → あって、まつ → まって'),
            ('ぶ, む, ぬ → んで','bu, mu, nu → nde','あそぶ → あそんで、よむ → よんで'),
            ('く → いて','ku → ite','かく → かいて (exception: いく → いって)'),
            ('ぐ → いで','gu → ide','およぐ → およいで (to swim)'),
            ('す → して','su → shite','はなす → はなして'),
        ]},
        {'type': 'grammar', 'title': 'Memorise this little song',
         'body': 'A classic mnemonic:<br><br><b>う・つ・る</b> → <b>って</b><br><b>ぶ・む・ぬ</b> → <b>んで</b><br><b>く</b> → <b>いて</b> (<i>except</i> いく → いって)<br><b>ぐ</b> → <b>いで</b><br><b>す</b> → <b>して</b><br><br>Chant this for a week until it&rsquo;s automatic. There is no shortcut.'},
        {'type': 'h2', 'text': 'Use 1: polite requests — ~てください'},
        {'type': 'p', 'text': 'Attach <b>ください</b> after the te-form to politely ask someone to do something.'},
        {'type': 'p', 'text': '<span class="inline-jp">ちょっと まってください。</span> &nbsp; <i>Chotto matte kudasai.</i> &nbsp; (Please wait a moment.)<br><span class="inline-jp">もういちど いってください。</span> &nbsp; (Please say it once more.)<br><span class="inline-jp">ここに なまえを かいてください。</span> &nbsp; (Please write your name here.)'},
        {'type': 'h2', 'text': 'Use 2: ongoing action — ~ています'},
        {'type': 'p', 'text': 'Attach <b>います</b> after the te-form to express an action in progress or a continuing state.'},
        {'type': 'p', 'text': '<span class="inline-jp">いま、ごはんを たべています。</span> &nbsp; (I am eating a meal right now.)<br><span class="inline-jp">かれは とうきょうに すんでいます。</span> &nbsp; (He lives in Tokyo.) — a state, not an action in progress<br><span class="inline-jp">しごとを しています。</span> &nbsp; (I&rsquo;m working.)'},
        {'type': 'h2', 'text': 'Use 3: connecting actions'},
        {'type': 'p', 'text': 'Use the te-form to chain actions in sequence — the equivalent of &ldquo;…and then…&rdquo; in English. Only the final verb carries the tense; the te-form inherits it.'},
        {'type': 'p', 'text': '<span class="inline-jp">あさ おきて、コーヒーを のんで、しごとに いきます。</span><br><i>Asa okite, koohii o nonde, shigoto ni ikimasu.</i><br>(In the morning I wake up, drink coffee, and go to work.)'},
        {'type': 'vocab', 'title': 'More verbs to practise', 'rows': [
            ('およぐ','oyogu','to swim'),
            ('あるく','aruku','to walk'),
            ('はしる','hashiru','to run (Group 1 trap!)'),
            ('すわる','suwaru','to sit'),
            ('たつ','tatsu','to stand'),
            ('はたらく','hataraku','to work'),
            ('やすむ','yasumu','to rest / take a day off'),
            ('わすれる','wasureru','to forget'),
            ('おぼえる','oboeru','to remember'),
            ('すむ','sumu','to live / reside'),
            ('わかる','wakaru','to understand'),
            ('しる','shiru','to know (usually used as しっています)'),
        ]},
        {'type': 'exercise', 'title': 'Exercises — Week 9', 'items': [
            'Form the te-form of: たべる、かく、まつ、はなす、よむ、する、くる、いく、およぐ、あそぶ.',
            'Translate: &ldquo;Please speak slowly.&rdquo; (Hint: slowly = <span class="inline-jp">ゆっくり</span>)',
            'Translate: &ldquo;I&rsquo;m reading a book now.&rdquo;',
            'Translate: &ldquo;Every day I wake up, eat breakfast, and go to school.&rdquo;',
            'Describe what you&rsquo;re doing right now in Japanese, using ~ています.',
        ]},
        {'type': 'resource', 'items': [
            '<b>Tae Kim — Compound Sentences &amp; the Te-form</b>',
            '<b>Game Gengo</b> on YouTube — a brilliant visual explanation of the te-form.',
            '<b>Renshuu</b> — set a drill for Group 1 te-form conjugation specifically.',
        ]},
    ],
})

# ============================== WEEK 10 ==============================
WEEKS.append({
    'num': 10,
    'title': 'Counters, Time, Dates',
    'goals': [
        'Tell the time (hours and minutes).',
        'Say days, months, and dates.',
        'Count objects using the right counter.',
        'Make simple appointments and schedules.',
    ],
    'sections': [
        {'type': 'h2', 'text': 'Telling time'},
        {'type': 'p', 'text': '<b>Hours:</b> attach <b>じ</b> (時) to a number. <b>Minutes:</b> attach <b>ふん / ぷん</b> (分). The minutes word changes sound depending on the preceding number.'},
        {'type': 'vocab', 'rows': [
            ('いちじ','ichi-ji','1 o&rsquo;clock'),
            ('よじ','yo-ji','4 o&rsquo;clock (not yon-ji)'),
            ('しちじ','shichi-ji','7 o&rsquo;clock'),
            ('くじ','ku-ji','9 o&rsquo;clock (not kyuu-ji)'),
            ('いっぷん','ippun','1 minute'),
            ('じゅっぷん','juppun','10 minutes'),
            ('はんぶん / はん','hanbun / han','half (as in half past the hour)'),
            ('ごぜん','gozen','AM / morning'),
            ('ごご','gogo','PM / afternoon'),
            ('ごぜん 7じ','gozen shichi-ji','7:00 AM'),
            ('ごご 3じはん','gogo san-ji han','3:30 PM'),
        ]},
        {'type': 'h2', 'text': 'Days of the week'},
        {'type': 'vocab', 'rows': [
            ('月曜日 / げつようび','getsu-youbi','Monday'),
            ('火曜日 / かようび','ka-youbi','Tuesday'),
            ('水曜日 / すいようび','sui-youbi','Wednesday'),
            ('木曜日 / もくようび','moku-youbi','Thursday'),
            ('金曜日 / きんようび','kin-youbi','Friday'),
            ('土曜日 / どようび','do-youbi','Saturday'),
            ('日曜日 / にちようび','nichi-youbi','Sunday'),
            ('今日 / きょう','kyou','today'),
            ('明日 / あした','ashita','tomorrow'),
            ('昨日 / きのう','kinou','yesterday'),
            ('今週 / こんしゅう','konshuu','this week'),
            ('来週 / らいしゅう','raishuu','next week'),
            ('先週 / せんしゅう','senshuu','last week'),
        ]},
        {'type': 'h2', 'text': 'Months and dates'},
        {'type': 'p', 'text': 'Months are easy: number + <b>がつ</b> (月). January = <b>いちがつ</b>, April = <b>しがつ</b> (not <i>yongatsu</i>!), September = <b>くがつ</b> (not <i>kyuugatsu</i>). Day-of-month is a mess for the first ten days (irregular) and tidy after:'},
        {'type': 'vocab', 'rows': [
            ('ついたち','tsuitachi','the 1st'),
            ('ふつか','futsuka','the 2nd'),
            ('みっか','mikka','the 3rd'),
            ('よっか','yokka','the 4th'),
            ('いつか','itsuka','the 5th'),
            ('むいか','muika','the 6th'),
            ('なのか','nanoka','the 7th'),
            ('ようか','youka','the 8th'),
            ('ここのか','kokonoka','the 9th'),
            ('とおか','tooka','the 10th'),
            ('じゅういちにち','juu-ichi-nichi','the 11th'),
            ('はつか','hatsuka','the 20th (irregular!)'),
        ]},
        {'type': 'p', 'text': '<b>Pattern after the 10th:</b> number + にち. Except <b>はつか</b> for the 20th and <b>よっか</b>/<b>ようか</b> flavoured endings on 14, 24. The irregular first ten are old native Japanese counting; they must be memorised. They&rsquo;re everywhere — invites, calendars, holidays — so put the effort in.'},
        {'type': 'h2', 'text': 'Counters: counting objects'},
        {'type': 'p', 'text': 'When counting objects in Japanese, you don&rsquo;t just say &ldquo;three book&rdquo;; you say &ldquo;book, three-[counter]&rdquo;. The counter depends on the shape or category of the thing being counted. Beginners need five or six to start.'},
        {'type': 'vocab', 'rows': [
            ('〜つ','-tsu','generic counter (1-10); ひとつ, ふたつ, みっつ…'),
            ('〜人 / 〜にん','-nin','people; ひとり, ふたり, さんにん…'),
            ('〜枚 / 〜まい','-mai','flat things (paper, tickets, shirts)'),
            ('〜本 / 〜ほん','-hon','long things (bottles, pens, umbrellas)'),
            ('〜匹 / 〜ひき','-hiki','small animals (cats, dogs, fish)'),
            ('〜個 / 〜こ','-ko','small round objects (apples, eggs)'),
            ('〜回 / 〜かい','-kai','times / occasions'),
            ('〜時間 / 〜じかん','-jikan','hours of duration'),
        ]},
        {'type': 'p', 'text': '<b>ひとつ, ふたつ, みっつ, よっつ, いつつ, むっつ, ななつ, やっつ, ここのつ, とお</b> — the generic counter 1–10. When in doubt about which counter to use, native speakers forgive <b>～つ</b>. For 11+, use regular numbers.'},
        {'type': 'h2', 'text': 'Example sentences'},
        {'type': 'p', 'text': '<span class="inline-jp">りんごを みっつ ください。</span> &nbsp; (Three apples, please.)<br><span class="inline-jp">まいにち 7じに おきます。</span> &nbsp; (I wake up at 7 every day.)<br><span class="inline-jp">らいしゅうの かようびに あいましょう。</span> &nbsp; (Let&rsquo;s meet next Tuesday.)<br><span class="inline-jp">わたしの いえには ねこが にひき います。</span> &nbsp; (I have two cats at my house.)'},
        {'type': 'exercise', 'title': 'Exercises — Week 10', 'items': [
            'Write the time: 8:15 AM, 3:30 PM, 11:45 PM.',
            'When is your friend&rsquo;s birthday? Write it in Japanese (month + day).',
            'How do you say &ldquo;five pens&rdquo;? &ldquo;Three dogs&rdquo;? &ldquo;Two tickets&rdquo;?',
            'Translate: &ldquo;Yesterday I slept for eight hours.&rdquo;',
            'Write a weekly schedule in Japanese: &ldquo;On Monday I work. On Saturday I rest.&rdquo; etc.',
        ]},
        {'type': 'resource', 'items': [
            '<b>Tofugu — Japanese Counters</b> — tofugu.com/japanese/japanese-counters',
            '<b>JapanesePod101 — Days, Months, Dates</b> playlist.',
            '<b>Jisho.org</b> — look up any word; it will show the appropriate counter.',
        ]},
    ],
})

# ============================== WEEK 11 ==============================
WEEKS.append({
    'num': 11,
    'title': 'Introduction to Kanji + The First 50',
    'goals': [
        'Understand what kanji is and how to read them.',
        'Learn on&rsquo;yomi vs kun&rsquo;yomi (Chinese vs Japanese readings).',
        'Recognise 50 common kanji on sight.',
        'Start spotting kanji in signs, menus, and simple text.',
    ],
    'sections': [
        {'type': 'h2', 'text': 'What is kanji?'},
        {'type': 'p', 'text': 'Kanji are Chinese characters adopted into Japanese roughly 1,500 years ago. Each one carries a meaning (sometimes several) and one or more pronunciations. There are around 2,000 in common adult use; the government&rsquo;s official <i>jōyō</i> list has 2,136. JLPT N5 asks for about 100 — what you&rsquo;ll learn in these final two weeks.'},
        {'type': 'grammar', 'title': 'on&rsquo;yomi and kun&rsquo;yomi',
         'body': 'Most kanji have at least two readings:<br><br><b>on&rsquo;yomi (音読み)</b> — the Chinese-origin reading, used mostly in compounds of two or more kanji. Often written in katakana in dictionaries.<br><br><b>kun&rsquo;yomi (訓読み)</b> — the native Japanese reading, used when the kanji stands alone or with hiragana endings. Written in hiragana in dictionaries.<br><br><b>Example:</b> 水 means &ldquo;water&rdquo;.<br>• kun&rsquo;yomi: <span class="inline-jp">みず</span> (<i>mizu</i>) — the word for water on its own<br>• on&rsquo;yomi: <span class="inline-jp">スイ</span> (<i>sui</i>) — used in <span class="inline-jp">水曜日 (すいようび)</span> &ldquo;Wednesday&rdquo;.'},
        {'type': 'h2', 'text': 'How to learn kanji well'},
        {'type': 'ul', 'items': [
            '<b>Learn in context, not in isolation.</b> Memorising a character with no words attached is wasted work. Learn 日 together with 日曜日, 今日, 日本.',
            '<b>Use spaced repetition.</b> WaniKani, Anki, or Renshuu — pick one and stick with it.',
            '<b>Learn radicals.</b> Many kanji are built from recurring pieces. 木 (tree) appears inside 森 (forest), 林 (grove), 村 (village).',
            '<b>Write them.</b> At least a few times, with stroke order. The hand teaches the eye.',
            '<b>Don&rsquo;t obsess over all readings at once.</b> Learn the reading that comes up in the word you&rsquo;re learning. More will stick naturally over time.',
        ]},
        {'type': 'h2', 'text': 'The first 50 N5 kanji'},
        {'type': 'p', 'text': 'Organised by theme. Tap any kanji to hear it spoken.'},
        {'type': 'h3', 'text': 'Numbers (10)'},
        {'type': 'kanji-grid', 'startAt': 1, 'items': [
            ('一','one','ichi — 一つ (hitotsu)'),
            ('二','two','ni — 二人 (futari)'),
            ('三','three','san — 三月 (sangatsu)'),
            ('四','four','yon / shi — 四月 (shigatsu)'),
            ('五','five','go — 五時 (goji)'),
            ('六','six','roku — 六本 (roppon)'),
            ('七','seven','nana / shichi — 七時'),
            ('八','eight','hachi — 八月'),
            ('九','nine','kyuu / ku — 九日'),
            ('十','ten','juu — 十人'),
        ]},
        {'type': 'h3', 'text': 'Days, time, calendar (10)'},
        {'type': 'kanji-grid', 'startAt': 11, 'items': [
            ('日','day / sun','hi / nichi — 日曜日, 今日'),
            ('月','moon / month','tsuki / getsu — 月曜日, 一月'),
            ('火','fire','hi / ka — 火曜日'),
            ('水','water','mizu / sui — 水曜日'),
            ('木','tree','ki / moku — 木曜日'),
            ('金','gold / money','kane / kin — 金曜日'),
            ('土','earth / soil','tsuchi / do — 土曜日'),
            ('曜','day of week','you — 曜日'),
            ('時','time / hour','toki / ji — 時間, 三時'),
            ('年','year','toshi / nen — 来年 (rainen)'),
        ]},
        {'type': 'h3', 'text': 'People and family (10)'},
        {'type': 'kanji-grid', 'startAt': 21, 'items': [
            ('人','person','hito / jin — 日本人, 一人'),
            ('男','man','otoko / dan — 男の人'),
            ('女','woman','onna / jo — 女の人'),
            ('子','child','ko / shi — 子ども'),
            ('父','father','chichi / fu — お父さん'),
            ('母','mother','haha / bo — お母さん'),
            ('友','friend','tomo / yuu — 友だち'),
            ('先','ahead / previous','saki / sen — 先生'),
            ('生','life / birth','iki / sei — 学生, 先生'),
            ('名','name','na / mei — 名前'),
        ]},
        {'type': 'h3', 'text': 'Position and direction (10)'},
        {'type': 'kanji-grid', 'startAt': 31, 'items': [
            ('大','big','oo / dai — 大学'),
            ('小','small','chii / shou — 小さい'),
            ('中','middle / inside','naka / chuu — 中国'),
            ('上','above / up','ue / jou — 上手'),
            ('下','below / down','shita / ka — 下さい'),
            ('前','before / in front','mae / zen — 名前'),
            ('後','after / behind','ushiro / go — 午後'),
            ('外','outside','soto / gai — 外国'),
            ('右','right side','migi / u — 右手'),
            ('左','left side','hidari / sa — 左手'),
        ]},
        {'type': 'h3', 'text': 'Body and nature (10)'},
        {'type': 'kanji-grid', 'startAt': 41, 'items': [
            ('口','mouth','kuchi / kou — 入口'),
            ('目','eye','me / moku — 目'),
            ('手','hand','te / shu — 右手, 上手'),
            ('足','foot / leg','ashi / soku'),
            ('耳','ear','mimi / ji'),
            ('力','power / strength','chikara / ryoku'),
            ('山','mountain','yama / san — 富士山'),
            ('川','river','kawa / sen'),
            ('田','rice field','ta / den — 田中'),
            ('円','yen / circle','en — 千円'),
        ]},
        {'type': 'exercise', 'title': 'Exercises — Week 11', 'items': [
            'Write each kanji five times with correct stroke order (use kakimashou.com).',
            'Read aloud: <span class="inline-jp">日本人、三月十日、お父さん、山の中、火曜日、大学生、先生、友だち</span>.',
            'Spot the kanji: in a Japanese menu photo or shop sign online, pick out any you now recognise.',
            'Add these 50 kanji to Anki or your SRS app. Review 20 minutes daily.',
            'Write a sentence using at least four of these kanji.',
        ]},
        {'type': 'resource', 'items': [
            '<b>WaniKani</b> — paid but worth it; teaches radicals → kanji → vocab in order.',
            '<b>Kanji Study</b> (Android) — free, excellent kanji practice app.',
            '<b>Jisho.org</b> — look up any kanji by radical, meaning, or stroke count.',
        ]},
    ],
})

# ============================== WEEK 12 ==============================
WEEKS.append({
    'num': 12,
    'title': '50 More Kanji + Reading Practice + Review',
    'goals': [
        'Add 50 more essential kanji (total: 100).',
        'Read a short passage in mixed Japanese.',
        'Review all grammar from the course.',
        'Plan what comes next.',
    ],
    'sections': [
        {'type': 'h2', 'text': 'The next 50 kanji'},
        {'type': 'h3', 'text': 'Verbs and actions (10)'},
        {'type': 'kanji-grid', 'startAt': 51, 'items': [
            ('行','to go','iku / kou — 行きます'),
            ('来','to come','kuru / rai — 来週'),
            ('食','to eat','taberu / shoku — 食事'),
            ('飲','to drink','nomu / in — 飲み物'),
            ('見','to see','miru / ken — 見ます'),
            ('聞','to hear / ask','kiku / bun — 新聞'),
            ('読','to read','yomu / doku — 読みます'),
            ('書','to write','kaku / sho — 書きます'),
            ('話','to speak','hanasu / wa — 話します, 電話'),
            ('買','to buy','kau / bai — 買います'),
        ]},
        {'type': 'h3', 'text': 'Places and transport (10)'},
        {'type': 'kanji-grid', 'startAt': 61, 'items': [
            ('家','house / home','ie / ka — 家族'),
            ('店','shop','mise / ten — お店'),
            ('駅','station','eki — 東京駅'),
            ('道','road / way','michi / dou — 道路'),
            ('町','town','machi / chou'),
            ('市','city','ichi / shi — 市場'),
            ('国','country','kuni / koku — 外国人'),
            ('車','car / vehicle','kuruma / sha — 電車'),
            ('電','electricity','den — 電話, 電車'),
            ('気','spirit / air','ki — 元気'),
        ]},
        {'type': 'h3', 'text': 'Nature and animals (10)'},
        {'type': 'kanji-grid', 'startAt': 71, 'items': [
            ('花','flower','hana / ka'),
            ('空','sky','sora / kuu — 空港'),
            ('雨','rain','ame / u'),
            ('天','heaven / weather','ten — 天気'),
            ('魚','fish','sakana / gyo'),
            ('犬','dog','inu / ken'),
            ('入','enter','iru / nyuu — 入ります, 入口'),
            ('出','exit','deru / shutsu — 出口'),
            ('休','rest','yasumu / kyuu — 休みます'),
            ('立','stand','tatsu / ritsu — 立ちます'),
        ]},
        {'type': 'h3', 'text': 'Study and language (10)'},
        {'type': 'kanji-grid', 'startAt': 81, 'items': [
            ('学','to learn','manabu / gaku — 学生, 大学'),
            ('校','school','kou — 学校'),
            ('高','high / expensive','takai / kou — 高校'),
            ('英','English','ei — 英語'),
            ('語','language','kataru / go — 日本語, 英語'),
            ('本','book / origin','hon / moto — 本, 日本'),
            ('文','sentence / writing','bun — 文学'),
            ('字','character / letter','ji — 漢字'),
            ('今','now','ima / kon — 今日, 今週'),
            ('半','half','han — 三時半'),
        ]},
        {'type': 'h3', 'text': 'Common and essential (10)'},
        {'type': 'kanji-grid', 'startAt': 91, 'items': [
            ('何','what','nani / nan — 何ですか'),
            ('百','hundred','hyaku — 三百'),
            ('千','thousand','sen — 千円'),
            ('万','ten thousand','man — 一万円'),
            ('午','noon / midday','go — 午前, 午後'),
            ('朝','morning','asa / chou — 朝ごはん'),
            ('昼','noon / daytime','hiru / chuu — 昼ごはん'),
            ('夜','night','yoru / ya'),
            ('新','new','atara / shin — 新しい, 新聞'),
            ('長','long / chief','naga / chou — 社長'),
        ]},
        {'type': 'h2', 'text': 'A short reading passage'},
        {'type': 'p', 'text': 'Read this slowly. Every grammar point and nearly every kanji in it was taught in this course. If you can decode it with your notes and a dictionary, you&rsquo;ve done the work.'},
        {'type': 'reading', 'text': 'わたしの なまえは アンナです。アメリカから きました。<br>いま、とうきょうに すんでいます。がくせいです。<br>まいにち あさ 7時に おきて、コーヒーを のんで、<br>がっこうに いきます。<br>ごごは ともだちと カフェで べんきょうします。<br>よるは うちで ばんごはんを たべて、日本の えいがを みます。<br>日本語は むずかしいですが、おもしろいです。'},
        {'type': 'h3', 'text': 'Translation'},
        {'type': 'p', 'text': 'My name is Anna. I come from America. I live in Tokyo now. I am a student. Every morning I wake up at 7, drink coffee, and go to school. In the afternoons I study with a friend at a café. In the evenings I eat dinner at home and watch Japanese movies. Japanese is difficult, but it&rsquo;s interesting.'},
        {'type': 'h2', 'text': 'Grammar review checklist'},
        {'type': 'ul', 'items': [
            'Topic / subject / object marked by は / が / を.',
            'Destination, time, location-of-existence with に; direction with へ.',
            'Location-of-action and means with で.',
            '&ldquo;And&rdquo; / &ldquo;with&rdquo; with と; &ldquo;also&rdquo; with も.',
            'Verb groups: Godan / Ichidan / する・くる.',
            'Polite present/future ~ます; polite negative ~ません.',
            'Polite past ~ました; past negative ~ませんでした.',
            'い-adjectives (おいしい → おいしくない → おいしかった) and な-adjectives (しずか + です).',
            'Te-form: requests ~てください, progressive ~ています, connecting actions.',
            'Numbers, time, dates, counters.',
        ]},
        {'type': 'h2', 'text': 'What comes next'},
        {'type': 'ul', 'items': [
            '<b>JLPT N5 practice tests.</b> Free ones are everywhere online. Sit one as a diagnostic.',
            '<b>Genki I (textbook)</b> if you want structure. The industry standard for English-speaking beginners.',
            '<b>Satori Reader</b> for extensive graded reading practice.',
            '<b>Comprehensible Japanese</b> on YouTube — hours of beginner-friendly listening.',
            '<b>Italki or Preply</b> — book a cheap conversation lesson with a native tutor. Nothing accelerates learning like being forced to produce the language.',
        ]},
        {'type': 'exercise', 'title': 'Final exercises — Week 12', 'items': [
            'Write 100 kanji in a single list, from memory. Mark the ones you got wrong and drill them.',
            'Translate the reading passage above without looking at the English translation.',
            'Write your own 150-word self-introduction, using as many kanji as you can.',
            'Record yourself speaking it. Listen back. Note three things to improve.',
            'Book your first conversation lesson. Really.',
        ]},
        {'type': 'resource', 'items': [
            '<b>JLPT Sensei</b> — practice tests and N5 grammar guides, free.',
            '<b>Genki I</b> — the standard beginner textbook (paid, but worth it).',
            '<b>Italki</b> — one-on-one tutor lessons starting around $10/hour.',
            '<b>Terrace House</b> on Netflix — natural, slow-paced Japanese conversation. Watch with Japanese subtitles.',
        ]},
        {'type': 'h2', 'text': 'A note at the end'},
        {'type': 'p', 'text': 'If you&rsquo;ve done the work in these twelve weeks, you&rsquo;ve done something small Japanese children spend six years on. Be patient with yourself. The next twelve weeks will feel slower than these — not because you&rsquo;re learning less, but because the easy wins (two scripts, basic grammar, your first 500 words) are behind you. The payoff is bigger: real conversations, real reading, a second mind forming in a second language.<br><br><b>がんばってください。</b> &nbsp; <i>Ganbatte kudasai.</i> &nbsp; (Please do your best.)'},
    ],
})
