# Data for the kana detail sheet: memory hooks, origins, look-alikes, voicing.
#
# Hooks are ORIGINAL to this course (do not copy published hook sets). They are
# memory aids, not history. `origin` IS history: the kanji each hiragana was
# simplified from (man'yōgana written in cursive) — shown as a fact.
# Romaji is not repeated here; build.py takes it from the kana charts.
#
# Batch 1: hiragana. Batch 2: katakana.

# (glyph, origin kanji, hook, (example word, reading, meaning))
HIRAGANA = [
    ('あ', '安', 'A cross with a loop swung through it — someone walking into a signpost: "Ah!"', ('あお', 'ao', 'blue')),
    ('い', '以', 'Two short strokes standing side by side, like the two i’s in "skiing".', ('いぬ', 'inu', 'dog')),
    ('う', '宇', 'A small cap over a wide curve — a hand cupped behind an ear: "Oo, what was that?"', ('うえ', 'ue', 'above')),
    ('え', '衣', 'A dash over a Z-shaped body with a kick at the foot — someone hopping on one leg: "Eh!"', ('えき', 'eki', 'station')),
    ('お', '於', 'Like あ, but with a dot flying off the top right — something flung away: "Oh!"', ('おちゃ', 'ocha', 'tea')),
    ('か', '加', 'A blade with a short slash beside it — a karate chop cutting the air: "Ka!"', ('かお', 'kao', 'face')),
    ('き', '幾', 'Two bars crossed by a slanting stick, the tail curling below — a kite’s frame and string.', ('きく', 'kiku', 'to listen')),
    ('く', '久', 'One bent stroke shaped like "<" — an arrow cueing you to look back: "ku(e)".', ('くに', 'kuni', 'country')),
    ('け', '計', 'A post beside a cross with a long tail — it looks like a lowercase k with an extra bar.', ('いけ', 'ike', 'pond')),
    ('こ', '己', 'Two short strokes, one above the other — two coins lying flat: "ko(in)".', ('こうえん', 'kouen', 'park')),
    ('さ', '左', 'A cross over a curve opening left — a little sake cup on its stand.', ('さかな', 'sakana', 'fish')),
    ('し', '之', 'One stroke that drops and swings up — a backwards J. Think "she" with a J’s swing.', ('した', 'shita', 'below')),
    ('す', '寸', 'A bar crossed by a stem that loops once — a soup ladle hanging from a rail: "su(p)".', ('すし', 'sushi', 'sushi')),
    ('せ', '世', 'A bar with two uprights, the right one folding down and back — a seat with its back: "se(at)".', ('せんせい', 'sensei', 'teacher')),
    ('そ', '曽', 'A lightning zig-zag that softens into a curl — a sharp "so!" that trails off.', ('そと', 'soto', 'outside')),
    ('た', '太', 'A cross with two short bars beside it — a table with two plates on it: "ta(ble)".', ('たべる', 'taberu', 'to eat')),
    ('ち', '知', 'Like さ, but the belly faces right — a chin jutting out: "chi(n)".', ('ちかい', 'chikai', 'near')),
    ('つ', '川', 'One wide wave lying on its side — say "tsu" with the hiss of air rushing over it.', ('なつ', 'natsu', 'summer')),
    ('て', '天', 'A bar that bends down into a curve — a hand reaching out. 手 (te) means "hand".', ('てんき', 'tenki', 'weather')),
    ('と', '止', 'A small slanted mark leaning on a C-curve — a torch resting in its holder: "to(rch)".', ('ともだち', 'tomodachi', 'friend')),
    ('な', '奈', 'A cross, a dot, and a loop tied below — a napkin knotted at a picnic: "na(pkin)".', ('なまえ', 'namae', 'name')),
    ('に', '仁', 'A post in front of two short bars — the bars are 二 (ni), "two".', ('にく', 'niku', 'meat')),
    ('ぬ', '奴', 'め with an extra curl on its tail — the curl is the "n" that turns め into ぬ.', ('いぬ', 'inu', 'dog')),
    ('ね', '祢', 'Like れ, but the tail ties off in a loop — a necktie knot: "ne(cktie)".', ('ねこ', 'neko', 'cat')),
    ('の', '乃', 'A single spiral — the most common character in Japanese; as a particle it means "of".', ('のむ', 'nomu', 'to drink')),
    ('は', '波', 'A post beside a cross with a loop — arms thrown out in a laugh: "Ha!"', ('はな', 'hana', 'flower')),
    ('ひ', '比', 'One stroke dipping like a shallow bowl, peaked at the left — a hill and its valley: "hi(ll)".', ('ひと', 'hito', 'person')),
    ('ふ', '不', 'Four separate strokes — a face puffing out a candle: "fu!" is barely more than breath.', ('ふるい', 'furui', 'old')),
    ('へ', '部', 'One low peak, like a hat — and almost identical in katakana (ヘ).', ('へや', 'heya', 'room')),
    ('ほ', '保', 'は with a lid on top — a hot pot with its lid on: "ho(t)".', ('ほん', 'hon', 'book')),
    ('ま', '末', 'Two bars, a stem and a loop at the foot — it is the right half of ほ standing alone.', ('まいにち', 'mainichi', 'every day')),
    ('み', '美', 'Looks like "21" written in a hurry — "mi" sounds like "me", and I’m 21.', ('みず', 'mizu', 'water')),
    ('む', '武', 'A cross, a long loop and a drop flicked away — a squiggle like a music mark: "mu(sic)".', ('むずかしい', 'muzukashii', 'difficult')),
    ('め', '女', 'Two crossing strokes closing in a soft loop — an eye with a lash. 目 (me) means "eye".', ('あめ', 'ame', 'rain')),
    ('も', '毛', 'し with two bars across it — two strokes "mo(re)" than し.', ('もくようび', 'mokuyoubi', 'Thursday')),
    ('や', '也', 'A curve, a dash and a long leaning stroke — a yacht’s sail heeling in the wind: "ya(cht)".', ('やま', 'yama', 'mountain')),
    ('ゆ', '由', 'A loop with a tall stroke through it. ゆ on a shop curtain marks a bathhouse — 湯 (yu), hot water.', ('ゆき', 'yuki', 'snow')),
    ('よ', '与', 'A short bar on a post that ends in a small loop — a hand raised in greeting: "Yo!"', ('よる', 'yoru', 'night')),
    ('ら', '良', 'A tick above a round belly — a rabbit’s ear over its back: "ra(bbit)".', ('らいしゅう', 'raishuu', 'next week')),
    ('り', '利', 'A short stroke beside a long flowing one — a bank and the river running by it: "ri(ver)".', ('りょこう', 'ryokou', 'travel')),
    ('る', '留', 'A zig-zag that ends in a closed loop — the route ends in a ring. Loop: る (ru). No loop: ろ (ro).', ('くるま', 'kuruma', 'car')),
    ('れ', '礼', 'A post with a stroke that zig-zags and kicks outward — someone beating a retreat: "re(treat)".', ('これ', 'kore', 'this')),
    ('ろ', '呂', 'る without the loop — the road stays open: "ro(ad)".', ('ろく', 'roku', 'six')),
    ('わ', '和', 'A post with a stroke that rolls into a wide arc — a wave breaking: "wa(ve)".', ('わたし', 'watashi', 'I / me')),
    ('を', '遠', 'Only ever the object particle, said "o". A bar, a zig-zag, a broken curve — tripping over an object: "Whoa!"', ('パンを たべます', 'pan o tabemasu', 'I eat bread')),
    ('ん', '无', 'One stroke shaped like a lowercase n with a tail — and it really is n.', ('えん', 'en', 'yen')),
]

# Katakana were taken from PART of a kanji (イ is the left of 伊); the sheet
# words the origin accordingly. origin None = disputed (ン); example None =
# not used in modern words (ヲ).
KATAKANA = [
    ('ア', '阿', 'A hook and one long leg — a capital A that lost its right side.', ('アメリカ', 'amerika', 'America')),
    ('イ', '伊', 'The "person" radical 亻 on its own — someone leaning on one foot: "ee".', ('イギリス', 'igirisu', 'UK')),
    ('ウ', '宇', 'The roof of 宇 with a chimney dot on top — a snug house: "oo".', ('ウール', 'uuru', 'wool')),
    ('エ', '江', 'A capital I standing on a plinth — the right part of 江. Think of an "e(levator)" shaft.', ('エンジニア', 'enjinia', 'engineer')),
    ('オ', '於', 'A cross with a leg kicked down-left — お with its loop taken off.', ('オレンジ', 'orenji', 'orange')),
    ('カ', '加', 'か without its extra tick — the 力 on the left of 加.', ('カメラ', 'kamera', 'camera')),
    ('キ', '幾', 'き without its bottom curl — two bars and a stick.', ('ケーキ', 'keeki', 'cake')),
    ('ク', '久', 'A short slash and a long sweep. Add a dash inside and it becomes タ; stretch the leg into a K and it’s ケ.', ('アイスクリーム', 'aisukuriimu', 'ice cream')),
    ('ケ', '介', 'The roof and right leg of 介 — a slanted K: "ke".', ('ケーキ', 'keeki', 'cake')),
    ('コ', '己', 'Two sides of a box, open on the left — the top of 己. Turn it a quarter and it’s ユ.', ('コーヒー', 'koohii', 'coffee')),
    ('サ', '散', 'A cross with an extra post — さ straightened out with a ruler.', ('サラダ', 'sarada', 'salad')),
    ('シ', '之', 'Two dots on the LEFT and a stroke that RISES from the bottom. (ツ: dots on top, stroke falls.)', ('タクシー', 'takushii', 'taxi')),
    ('ス', '須', 'A hook with a leg kicking out to the right — a sprinter pushing off: "su(dden)".', ('バス', 'basu', 'bus')),
    ('セ', '世', 'せ with its right side folded short — the same seat, seen from the side.', ('セーター', 'seetaa', 'sweater')),
    ('ソ', '曽', 'Two strokes, both coming DOWN from the top. (ン’s long stroke rises from below.)', ('ソファー', 'sofaa', 'sofa')),
    ('タ', '多', 'ク with a dash inside — one 夕 from 多 ("many" is two of them stacked).', ('タクシー', 'takushii', 'taxi')),
    ('チ', '千', 'It is 千 (thousand) with its top stroke tilted — "chi" for a thousand.', ('チーズ', 'chiizu', 'cheese')),
    ('ツ', '川', 'Three strokes like 川 (river) tipped over: dots ON TOP, the long stroke falling from the right.', ('スポーツ', 'supootsu', 'sport')),
    ('テ', '天', 'Two bars and a hanging stroke — 天 with its legs cut off; て straightened.', ('テレビ', 'terebi', 'television')),
    ('ト', '止', 'One post with a twig to the right — a signpost pointing "to" the right.', ('トイレ', 'toire', 'toilet')),
    ('ナ', '奈', 'An upright cross with a long left leg — the top of 奈. (メ is the tilted X.)', ('カナダ', 'kanada', 'Canada')),
    ('ニ', '仁', 'Two bars, the lower one longer — the 二 (two) on the right of 仁.', ('ニュース', 'nyuusu', 'news')),
    ('ヌ', '奴', 'A 7 with a slash cut through it — the 又 on the right of 奴; フ with a cut.', ('ヌードル', 'nuudoru', 'noodles')),
    ('ネ', '祢', 'The altar radical 礻 from 祢 — a little shrine on a post: "ne".', ('インターネット', 'intaanetto', 'internet')),
    ('ノ', '乃', 'One falling stroke — the first stroke of 乃. The simplest katakana there is.', ('ノート', 'nooto', 'notebook')),
    ('ハ', '八', 'It is 八 (eight): two strokes parting like a laugh breaking out — "ha".', ('ハンバーガー', 'hanbaagaa', 'hamburger')),
    ('ヒ', '比', 'The right half of 比 — a short bar and a hook, like a shoe heel: "hee(l)".', ('コーヒー', 'koohii', 'coffee')),
    ('フ', '不', 'One stroke across then down — a hook hanging from a ceiling; the top of 不.', ('フランス', 'furansu', 'France')),
    ('ヘ', '部', 'Same shape as hiragana へ — one low peak.', ('ヘリコプター', 'herikoputaa', 'helicopter')),
    ('ホ', '保', 'A cross with two little feet — the 木 in the corner of 保; ほ squared off.', ('ホテル', 'hoteru', 'hotel')),
    ('マ', '末', 'A bent stroke closed by a short tick inside — a ladle. (ア has a long leg instead.)', ('トマト', 'tomato', 'tomato')),
    ('ミ', '三', 'Three slanted strokes — 三 (three) tilted. "Mi" for three of me.', ('ミルク', 'miruku', 'milk')),
    ('ム', '牟', 'A triangle missing one side — the top of 牟; a mouth half open, mute: "mu".', ('ゲーム', 'geemu', 'game')),
    ('メ', '女', 'An X — two strokes crossing, taken from 女. X marks the spot: "me".', ('メキシコ', 'mekishiko', 'Mexico')),
    ('モ', '毛', 'Two bars on a hooked post — 毛 (hair) trimmed; も with straighter lines.', ('レモン', 'remon', 'lemon')),
    ('ヤ', '也', 'A tilted hook and one stroke — や without its little dash.', ('タイヤ', 'taiya', 'tyre')),
    ('ユ', '由', 'An open box with a long base — コ turned a quarter. You can sit in it: "yu".', ('ユーロ', 'yuuro', 'euro')),
    ('ヨ', '与', 'Three bars on a spine — a backwards E.', ('ヨーグルト', 'yooguruto', 'yogurt')),
    ('ラ', '良', 'A dash over a 7-shaped hook — the top of 良; ら with a lid instead of a tick.', ('ラーメン', 'raamen', 'ramen')),
    ('リ', '利', 'Two strokes, the right one longer — the knife radical 刂 of 利; り squared off.', ('イタリア', 'itaria', 'Italy')),
    ('ル', '流', 'Two legs, the right one kicking up — the bottom of 流; a figure breaking into a "ru(n)".', ('ホテル', 'hoteru', 'hotel')),
    ('レ', '礼', 'One stroke down and sharply up — a tick mark: "re"(viewed).', ('レストラン', 'resutoran', 'restaurant')),
    ('ロ', '呂', 'A square — the top box of 呂; like 口 (mouth), a small "ro"om.', ('ロボット', 'robotto', 'robot')),
    ('ワ', '和', 'ウ without its chimney dot — a short post and a wide hook.', ('ワイン', 'wain', 'wine')),
    ('ヲ', '乎', 'The katakana for the particle を. Modern Japanese writes を instead; you’ll see ヲ in old texts and games.', None),
    ('ン', None, 'A dot and a long stroke RISING from the bottom left — the reverse motion of ソ.', ('パン', 'pan', 'bread')),
]

# (base, voiced form, mark). Explicit on purpose — no codepoint arithmetic.
VOICED = [
    ('か', 'が', '゛'), ('き', 'ぎ', '゛'), ('く', 'ぐ', '゛'), ('け', 'げ', '゛'), ('こ', 'ご', '゛'),
    ('さ', 'ざ', '゛'), ('し', 'じ', '゛'), ('す', 'ず', '゛'), ('せ', 'ぜ', '゛'), ('そ', 'ぞ', '゛'),
    ('た', 'だ', '゛'), ('ち', 'ぢ', '゛'), ('つ', 'づ', '゛'), ('て', 'で', '゛'), ('と', 'ど', '゛'),
    ('は', 'ば', '゛'), ('ひ', 'び', '゛'), ('ふ', 'ぶ', '゛'), ('へ', 'べ', '゛'), ('ほ', 'ぼ', '゛'),
    ('は', 'ぱ', '゜'), ('ひ', 'ぴ', '゜'), ('ふ', 'ぷ', '゜'), ('へ', 'ぺ', '゜'), ('ほ', 'ぽ', '゜'),
    ('カ', 'ガ', '゛'), ('キ', 'ギ', '゛'), ('ク', 'グ', '゛'), ('ケ', 'ゲ', '゛'), ('コ', 'ゴ', '゛'),
    ('サ', 'ザ', '゛'), ('シ', 'ジ', '゛'), ('ス', 'ズ', '゛'), ('セ', 'ゼ', '゛'), ('ソ', 'ゾ', '゛'),
    ('タ', 'ダ', '゛'), ('チ', 'ヂ', '゛'), ('ツ', 'ヅ', '゛'), ('テ', 'デ', '゛'), ('ト', 'ド', '゛'),
    ('ハ', 'バ', '゛'), ('ヒ', 'ビ', '゛'), ('フ', 'ブ', '゛'), ('ヘ', 'ベ', '゛'), ('ホ', 'ボ', '゛'),
    ('ハ', 'パ', '゜'), ('ヒ', 'ピ', '゜'), ('フ', 'プ', '゜'), ('ヘ', 'ペ', '゜'), ('ホ', 'ポ', '゜'),
]

# Characters learners confuse. Each string is one group; every member lists the
# others. Members without a record (工 力 二 口, outside the course) are still
# shown, just not tappable.
LOOKALIKE_GROUPS = [
    # hiragana
    'さち', 'さき', 'ぬめ', 'るろ', 'いり', 'れわね', 'はほ', 'あお', 'こに', 'うら',
    # across scripts
    'へヘ', 'りリ', 'かカ', 'きキ', 'やヤ',
    # katakana
    'シツ', 'ソン', 'クケタ', 'ウワフ', 'ユコ', 'ナメ', 'エ工', 'カ力', 'ニ二', 'ロ口',
]

# ------------------------------------------------------------------ kanji
# glyph -> (hook, origin or None, parts). Meaning and readings come from
# content_kanji.py. `origin` only where it is textbook-standard (pictographs and
# a few indicatives) — tests/test_glyphs.py pins the allowed set. `parts` are
# visible components, each checked against KRADFILE (EDRDG, CC BY-SA 4.0).
KANJI_HOOKS = {
    '一': ('One stroke, one thing — the simplest kanji there is.', 'A single tally stroke.', []),
    '二': ('Two strokes, two things — the lower one longer, a shelf under a shelf.', 'Two tally strokes.', []),
    '三': ('Three strokes, three things — top and bottom long, the middle shortest.', 'Three tally strokes.', []),
    '四': ('A box with two legs inside — four walls around a pair: four.', None, []),
    '五': ('Two bars sandwiching a twisted stroke — an hourglass on its side: five.', None, []),
    '六': ('A lid with a dot on top and two legs below — a little hut: six.', None, []),
    '七': ('A cross whose foot hooks to the right — a 7 turned upside down.', None, []),
    '八': ('Two strokes splitting apart like a road forking — eight. Katakana ハ is the same shape.', None, []),
    '九': ('Like 力 with its leg kicked out — nine, one short of ten and still reaching.', None, []),
    '十': ('A plain cross — ten, like the Roman X stood upright.', None, []),
    '日': ('The circle became a box and the dot became the middle bar. One sun, one day.', 'A drawing of the sun: a circle with a dot in the middle.', []),
    '月': ('The crescent was stood upright; the two bars inside are what is left of its shading. Also "month".', 'A crescent moon.', []),
    '火': ('The sparks became the two side ticks; the flame is the 人-like shape underneath.', 'Flames rising, with sparks on both sides.', []),
    '水': ('The stream became the hooked middle stroke; the splashes are the strokes to either side.', 'A stream with drops splashing out on either side.', []),
    '木': ('The branches became the cross bar; the roots became the two slanting strokes at the foot.', 'A tree: branches above, roots below the trunk.', []),
    '金': ('A roof over 王 with two nuggets beside it — gold buried under a hill. Also "money".', None, [['王', 'king']]),
    '土': ('A short cross on a long base — a sprout pushing up out of the earth.', None, []),
    '曜': ('The sun 日 beside a bird 隹 with wings — the weekdays are named after sun, moon and planets.', None, [['日', 'sun'], ['隹', 'bird']]),
    '時': ('The sun 日 beside a temple 寺 — temple bells used to tell the hours.', None, [['日', 'sun'], ['寺', 'temple']]),
    '年': ('A figure carrying a sheaf of grain — one harvest, one year.', None, []),
    '人': ('Only the walking legs survived: two strokes leaning together. The left one is longer (in 入 it’s the right).', 'A person seen from the side, walking.', []),
    '男': ('A field 田 over strength 力 — the one who worked the fields: man.', None, [['田', 'rice field'], ['力', 'power']]),
    '女': ('The kneeling legs became the bent strokes; the crossed arms are the long bar.', 'A woman kneeling, arms crossed in front.', []),
    '子': ('The head is the top hook, the arms the cross bar, the wrapped body the hooked stem.', 'A swaddled baby with its arms out.', []),
    '父': ('Two ticks over crossed strokes — a pair of crossed tools in a father’s hands.', None, []),
    '母': ('A frame with two dots inside — a mother holding two children close.', '女 (woman) with two dots added: mother.', []),
    '友': ('Two hands, one over the other — 又 is an old drawing of a hand: friends shaking hands.', None, [['又', 'hand']]),
    '先': ('A foot stepping out ahead of a person’s legs 儿 — going first: ahead.', None, [['儿', 'legs']]),
    '生': ('You already know it from 先生 (teacher, "born before") and 学生 (student).', 'A plant sprouting from the earth.', []),
    '名': ('Evening 夕 plus mouth 口 — in the dark you call out your name.', None, [['夕', 'evening'], ['口', 'mouth']]),
    '大': ('The arms became the cross bar and the legs the two sweeping strokes — a person as big as they can be.', 'A person standing with arms and legs spread.', []),
    '小': ('A hooked stem with a grain dropped on each side — small bits.', None, []),
    '中': ('A line straight through the middle of a box — an arrow hitting the centre.', None, []),
    '上': ('Picture the short stroke as a flag planted on top of the line: up, above.', 'An indicative sign: a mark above a line.', []),
    '下': ('The stroke hangs below the line like a weight on a string: down, below.', 'An indicative sign: a mark below a line.', []),
    '前': ('Two horns over a moon 月 and a knife 刂 — cutting forward through what’s in front.', None, [['月', 'moon / flesh'], ['刂', 'knife']]),
    '後': ('Small steps 彳, a thread 幺 and a dragging foot 夂 — trailing behind: after.', None, [['彳', 'going'], ['幺', 'thread'], ['夂', 'trailing foot']]),
    '外': ('Evening 夕 and a divination crack 卜 — reading omens at night, outside.', None, [['夕', 'evening'], ['卜', 'divination']]),
    '右': ('A hand over a mouth 口 — the hand you eat with: right.', None, [['口', 'mouth']]),
    '左': ('A hand over a tool 工 — the hand that steadies the tool: left.', None, [['工', 'craft / tool']]),
    '口': ('The open lips were squared off into a box. Also an opening, an entrance.', 'An open mouth.', []),
    '目': ('The eye was turned on end; the two bars inside are the iris and the lids.', 'An eye, later turned upright.', []),
    '手': ('The fingers became three crossing strokes; the arm is the hooked stem.', 'A hand with the fingers spread.', []),
    '足': ('A knee 口 above a foot 止 — the whole leg down to the foot.', None, [['口', 'box — the knee'], ['止', 'stop / foot']]),
    '耳': ('The outline of the ear became the frame; its inner folds are the two bars.', 'An ear.', []),
    '力': ('An arm flexed hard, or a plough biting the soil — power. (Katakana カ is the same shape.)', None, []),
    '山': ('Three peaks became three uprights on a base — the middle one still the tallest.', 'Three mountain peaks.', []),
    '川': ('Three currents became three strokes; the left one still curves like flowing water.', 'Water flowing between banks.', []),
    '田': ('The plots stayed as they were: a square cut into four paddies.', 'A field divided into plots.', []),
    '円': ('A frame with a stroke inside — a coin purse: yen. The old form 圓 meant "round".', None, []),
    '行': ('A short step 彳 and its partner — two paths meeting: to go.', 'A crossroads seen from above.', [['彳', 'going']]),
    '来': ('A cross with two ticks and spreading legs — wheat ears arriving at harvest: to come.', None, []),
    '食': ('A lid over a full bowl — food, to eat.', None, []),
    '飲': ('Food 食 beside a wide-open mouth 欠 — taking in a drink.', None, [['食', 'eat'], ['欠', 'gaping mouth']]),
    '見': ('An eye 目 on legs 儿 — an eye walking about: to see.', None, [['目', 'eye'], ['儿', 'legs']]),
    '聞': ('An ear 耳 at the gate 門 — listening at the door: to hear.', None, [['門', 'gate'], ['耳', 'ear']]),
    '読': ('Words 言 + sell 売 — a seller reading his wares aloud: to read.', None, [['言', 'words'], ['売', 'sell']]),
    '書': ('A hand holding a brush 聿 over the sun 日 — writing by daylight.', None, [['聿', 'brush'], ['日', 'sun']]),
    '話': ('Words 言 + tongue 舌 — to speak.', None, [['言', 'words'], ['舌', 'tongue']]),
    '買': ('A net 罒 over a shell 貝 — shells were money: to buy.', None, [['罒', 'net'], ['貝', 'shell (money)']]),
    '家': ('A roof 宀 over a pig 豕 — the farmhouse where the pig lived: house.', None, [['宀', 'roof'], ['豕', 'pig']]),
    '店': ('A lean-to 广 with a fortune-teller’s stall 占 under it — a shop.', None, [['广', 'building'], ['占', 'divine / occupy']]),
    '駅': ('A horse 馬 at a post — horses were changed at stations.', None, [['馬', 'horse']]),
    '道': ('A head 首 on the move 辶 — walking with your head up: road, way.', None, [['首', 'head'], ['辶', 'movement']]),
    '町': ('A field 田 and a block 丁 — fields laid out into town blocks.', None, [['田', 'rice field'], ['丁', 'block']]),
    '市': ('A lid over cloth 巾 on a pole — a market stall’s banner: market, city.', None, [['巾', 'cloth']]),
    '国': ('A jewel 玉 inside a border 囗 — a country guarding its treasure.', None, [['囗', 'enclosure'], ['玉', 'jewel']]),
    '車': ('From above: the axle is the long vertical, the wheels the top and bottom bars, the body the box.', 'A cart seen from above: axle, wheels and body.', []),
    '電': ('Rain 雨 above a bolt of lightning — electricity.', None, [['雨', 'rain']]),
    '気': ('Steam 气 rising off a pot — spirit, air, mood.', None, [['气', 'vapour']]),
    '花': ('Grass 艹 over change 化 — the plant that changes into bloom: flower.', None, [['艹', 'grass'], ['化', 'change']]),
    '空': ('A hole 穴 over craft 工 — the empty space overhead: sky.', None, [['穴', 'hole'], ['工', 'craft']]),
    '雨': ('The sky is the top bar, the cloud the frame, and the four ticks inside are the drops.', 'Drops falling from a cloud beneath the sky.', []),
    '天': ('A line above a big person 大 — the sky over our heads: heaven.', None, [['一', 'line (the sky)'], ['大', 'big person']]),
    '魚': ('The head sits on top, the scaled body became 田, and the tail fins are the four dots below.', 'A fish: head, scaled body, tail fins.', []),
    '犬': ('Now written as 大 (big) with a dot — a big dog with one ear pricked up.', 'A dog.', [['大', 'big'], ['丶', 'dot']]),
    '入': ('Two strokes leaning in, the right one longer — stepping in: enter. (In 人 the left is longer.)', None, []),
    '出': ('Two mountains 山 stacked — climbing out over them: exit, to go out.', None, [['山', 'mountain']]),
    '休': ('A person 亻 leaning on a tree 木 — taking a rest.', None, [['亻', 'person'], ['木', 'tree']]),
    '立': ('The dot is the head, the two ticks the arms, and the long base the ground under the feet.', 'A person standing on the ground.', []),
    '学': ('A child 子 under a roof 冖 with sparks ⺌ above — learning in the schoolhouse.', None, [['⺌', 'sparks'], ['冖', 'cover'], ['子', 'child']]),
    '校': ('Tree 木 + mix 交 — where people mix under the trees: school.', None, [['木', 'tree'], ['交', 'mix']]),
    '高': ('A tall tower: roof, window, and a gate below — tall, high, expensive.', None, []),
    '英': ('Grass 艹 with centre 央 — the finest bloom in the middle; today it means "English".', None, [['艹', 'grass']]),  # 央 omitted: KRADFILE lists 英 without 央's 一
    '語': ('Words 言 + I 吾 — the words I speak: language.', None, [['言', 'words'], ['吾', 'I']]),
    '本': ('Root of a tree → origin → where things come from: book. 日本 is "origin of the sun".', 'A tree 木 with a mark at its root.', [['木', 'tree']]),
    '文': ('A figure with crossed lines on its chest — patterns, then writing: sentence.', None, []),
    '字': ('A child 子 under a roof 宀 — characters are raised at home: letter.', None, [['宀', 'roof'], ['子', 'child']]),
    '今': ('A lid closing over a single line — this moment, captured: now.', None, []),
    '半': ('Two ticks over a cross split down the middle — something cut in half.', None, []),
    '何': ('A person 亻 + can 可 — "what can a person do?": what.', None, [['亻', 'person'], ['可', 'can']]),
    '百': ('One 一 over white 白 — one hundred.', None, [['一', 'one'], ['白', 'white']]),
    '千': ('A stroke slanting over ten 十 — ten, then a thousand.', None, [['十', 'ten']]),
    '万': ('One 一 with a long hooked tail — ten thousand, a number that trails on.', None, []),
    '午': ('A pestle standing upright — noon. (牛, cow, has a horn poking through the top.)', None, []),
    '朝': ('The sun 日 rising through the grass while the moon 月 is still out — morning.', None, [['日', 'sun'], ['月', 'moon']]),
    '昼': ('The sun 日 standing over the horizon line — daytime, noon.', None, [['日', 'sun']]),
    '夜': ('A person 亻 under a roof in the evening 夕 — night.', None, [['亻', 'person'], ['夕', 'evening']]),
    '新': ('Stand 立 by a tree 木 with an axe 斤 — freshly cut: new.', None, [['立', 'stand'], ['木', 'tree'], ['斤', 'axe']]),
    '長': ('Long hair streaming down — long; and the elder with the long hair: chief.', None, []),
}

# Look-alikes among kanji, and across scripts (katakana borrowed many shapes).
LOOKALIKE_GROUPS += ['人入八', '大犬天', '日目', '木本', '右左', '千十', '八ハ', 'タ夕', 'ト卜', 'ミ三']

# Simple line drawings of what the 20 pictographs depict (100x100 canvas,
# stroked in currentColor; build.py wraps them in the <svg> element).
KANJI_SVG = {
    '日': '<circle cx="50" cy="50" r="32"/><circle cx="50" cy="50" r="4"/>',
    '月': '<path d="M62 14 A36 36 0 1 0 62 86 A28 28 0 1 1 62 14 Z"/>',
    '火': '<path d="M50 88 C30 82 28 60 40 46 C42 56 48 58 50 50 C52 38 48 28 44 14 C62 26 74 46 70 66 C68 80 60 88 50 88 Z"/><path d="M20 38 L28 52"/><path d="M80 38 L72 52"/>',
    '水': '<path d="M50 10 C40 30 60 52 48 90"/><path d="M24 30 C32 42 32 54 24 66"/><path d="M76 30 C68 42 68 54 76 66"/>',
    '木': '<path d="M50 10 V90"/><path d="M50 42 L24 22"/><path d="M50 42 L76 22"/><path d="M50 72 L28 90"/><path d="M50 72 L72 90"/>',
    '山': '<path d="M8 86 L28 44 L40 64 L50 14 L60 64 L72 44 L92 86 Z"/>',
    '川': '<path d="M28 12 C20 40 36 60 24 90"/><path d="M50 12 C42 40 58 60 46 90"/><path d="M72 12 C64 40 80 60 68 90"/>',
    '田': '<rect x="14" y="14" width="72" height="72" rx="4"/><path d="M50 14 V86"/><path d="M14 50 H86"/><path d="M30 34 v-6 M66 34 v-6 M30 70 v-6 M66 70 v-6"/>',
    '口': '<path d="M14 50 C28 26 72 26 86 50 C72 76 28 76 14 50 Z"/><path d="M24 50 H76"/>',
    '目': '<path d="M8 50 C28 24 72 24 92 50 C72 76 28 76 8 50 Z"/><circle cx="50" cy="50" r="13"/><circle cx="50" cy="50" r="3"/>',
    '耳': '<path d="M40 12 C72 8 86 36 74 58 C68 70 58 68 56 80 C54 92 38 94 32 82"/><path d="M48 30 C62 28 66 44 56 52"/>',
    '手': '<circle cx="50" cy="62" r="16"/><path d="M50 46 V10"/><path d="M42 48 L30 16"/><path d="M58 48 L70 16"/><path d="M36 56 L14 40"/><path d="M50 78 V92"/>',
    '人': '<circle cx="58" cy="16" r="8"/><path d="M56 26 L42 90"/><path d="M48 58 L70 90"/><path d="M52 40 L72 50"/>',
    '子': '<circle cx="50" cy="22" r="12"/><path d="M22 46 C36 40 64 40 78 46"/><path d="M50 34 C56 58 54 76 40 90"/>',
    '女': '<circle cx="50" cy="16" r="9"/><path d="M50 26 C42 46 38 62 30 88"/><path d="M50 26 C58 46 64 64 74 88"/><path d="M22 50 L80 44"/><path d="M30 88 H74"/>',
    '大': '<circle cx="50" cy="16" r="9"/><path d="M50 26 V58"/><path d="M16 40 H84"/><path d="M50 58 L24 90"/><path d="M50 58 L76 90"/>',
    '雨': '<path d="M10 16 H90"/><path d="M18 30 C24 20 40 22 44 28 C50 18 70 20 74 30 C84 30 88 40 80 44 H22 C12 44 12 32 18 30 Z"/><path d="M28 56 L26 66 M50 56 L48 66 M72 56 L70 66 M38 74 L36 84 M62 74 L60 84"/>',
    '魚': '<path d="M12 50 C28 26 64 26 78 50 C64 74 28 74 12 50 Z"/><path d="M78 50 L92 36 V64 Z"/><circle cx="26" cy="46" r="3"/><path d="M40 40 C46 46 46 54 40 60 M54 40 C60 46 60 54 54 60"/>',
    '犬': '<path d="M16 54 C26 42 58 42 68 50 L80 36 L88 44 L80 58 C78 70 74 80 74 90"/><path d="M26 56 L24 90"/><path d="M62 60 L64 90"/><path d="M16 54 L8 40"/><circle cx="80" cy="46" r="2"/>',
    '車': '<rect x="32" y="32" width="36" height="36" rx="3"/><path d="M50 10 V90"/><path d="M26 14 H74"/><path d="M26 86 H74"/>',
}
